### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/probability#1151]
on implementing this on colab after git clone:
`!python /content/probability/tensorflow_probability/examples/bayesian_neural_network.py`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/seaborn/_core.py", line 1456, in categorical_order
    order = vector.cat.categories
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'cat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/seaborn/_core.py", line 1460, in categorical_order
    order = vector.unique()
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'unique'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/probability/tensorflow_probability/examples/bayesian_neural_network.py", line 366, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/probability/tensorflow_probability/examples/bayesian_neural_network.py", line 362, in main
    .format(heldout_log_prob))
  File "/content/probability/tensorflow_probability/examples/bayesian_neural_network.py", line 150, in plot_heldout_prediction
    sns.barplot(np.arange(10), prob_sample[i, :], alpha=0.1, ax=ax)
  File "/usr/local/lib/python3.6/dist-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py", line 3172, in barplot
    errcolor, errwidth, capsize, dodge)
  File "/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py", line 1585, in __init__
    order, hue_order, units)
  File "/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py", line 203, in establish_variables
    group_names = categorical_order(groups, order)
  File "/usr/local/lib/python3.6/dist-packages/seaborn/_core.py", line 1462, in categorical_order
    order = pd.unique(vector)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/algorithms.py", line 390, in unique
    uniques = _reconstruct_data(uniques, original.dtype, original)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/algorithms.py", line 208, in _reconstruct_data
    values = values.astype(dtype, copy=False)
TypeError: data type not understood`

**Comment by asifalikhan** [comment]
in colab 
!pip install seaborn==0.10.0
work for me.
