### ISSUE TITLE
Error with seaborn in examples/bayesian_neural_network.py

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/probability#1209]
Request for help for bayesian_neural_network.py
I am trying to run the examples/bayesian_neural_network.py

### **_Trial 1: without seaborn_**

1. Program runs, but the graphs are not stored in the folder

### **_Trial 2: with seaborn_** (**_error_**, program stops and the graphs are not stored in the 'bayesian_neural_network' folder)
Version: 
seaborn-0.11.1
tensorflow==2.4.0
tensorflow-estimator==2.4.0
tensorflow-probability==0.12.1

Error: while " Running monte carlo inference" after the 1st 400th step (ie. viz_steps=400) and trying for "plot_heldout_prediction". Error details are shared below

### 
**_Error Details in "plot_heldout_prediction"_**

`saved /..../bayesian_neural_network/epoch0_step00399_weights.png
Traceback (most recent call last):
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/_core.py", line 1472, in categorical_order
    order = vector.cat.categories
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'cat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/_core.py", line 1476, in categorical_order
    order = vector.unique()
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'unique'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BNN_trial_1.py", line 366, in <module>
    app.run(main)
  File "/home/..../tf_latest/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/..../tf_latest/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "BNN_trial_1.py", line 362, in main
    .format(heldout_log_prob))
  File "BNN_trial_1.py", line 150, in plot_heldout_prediction
    sns.barplot(np.arange(10), prob_sample[i, :], alpha=0.1, ax=ax)
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/categorical.py", line 3182, in barplot
    errcolor, errwidth, capsize, dodge)
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/categorical.py", line 1585, in __init__
    order, hue_order, units)
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/categorical.py", line 203, in establish_variables
    group_names = categorical_order(groups, order)
  File "/home/..../tf_latest/lib/python3.6/site-packages/seaborn/_core.py", line 1478, in categorical_order
    order = pd.unique(vector)
  File "/home/..../tf_latest/lib/python3.6/site-packages/pandas/core/algorithms.py", line 400, in unique
    uniques = _reconstruct_data(uniques, original.dtype, original)
  File "/home/..../tf_latest/lib/python3.6/site-packages/pandas/core/algorithms.py", line 218, in _reconstruct_data
    values = values.astype(dtype, copy=False)
TypeError: Cannot interpret 'tf.float32' as a data type`

Please support to solve this error.

**Comment by europeanplaice** [comment]
How about converting the tensor to a pd.Series? You may have applied pandas' operation to TensorFlow tensor.
It is a cause of the error.

**Comment by emilyfertig** [comment]
Fixed by 09bcb282450bab8b8860b89385aeee1feaeaeb5d (as noted in #1409)
