### ISSUE TITLE
tfp.bijectors.BatchNormalization breaks with dynamic batch size

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#121]
python version: 3.6.5
tensorflow version: 1.9.0
tensorflow-probability version: 0.2.0

The BatchNormalization bijector does not currently work for dynamic batch size. I have the following code:
```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp


tfb = tfp.bijectors
tf.set_random_seed(1)


def test_batchnorm_with_axis(axis):
    x = tf.placeholder(tf.float32, shape=(None, 32, 32, 3))
    x_num = np.random.uniform(size=(3, 32, 32, 3))

    z = tfb.BatchNormalization(
        batchnorm_layer=tf.layers.BatchNormalization(axis=axis)
    ).forward(x)

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        z_num = sess.run(z, feed_dict={x: x_num})

    return z_num
```

```
>>> test_batchnorm_with_axis(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kristian/code/glow-flow/broken_tfb_batchnorm.py", line 16, in test_batchnorm_with_axis
    ).forward(x)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bijector_impl.py", line 764, in forward
    return self._call_forward(x, name)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bijector_impl.py", line 745, in _call_forward
    mapping = mapping.merge(y=self._forward(x, **kwargs))
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/batch_normalization.py", line 223, in _forward
    return self._de_normalize(x)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/batch_normalization.py", line 213, in _de_normalize
    self.batchnorm.build(input_shape)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 262, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(None), Dimension(32), Dimension(32), Dimension(3)]))
```

```
>>> test_batchnorm_with_axis(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kristian/code/glow-flow/broken_tfb_batchnorm.py", line 16, in test_batchnorm_with_axis
    ).forward(x)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bijector_impl.py", line 764, in forward
    return self._call_forward(x, name)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bijector_impl.py", line 745, in _call_forward
    mapping = mapping.merge(y=self._forward(x, **kwargs))
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/batch_normalization.py", line 223, in _forward
    return self._de_normalize(x)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/batch_normalization.py", line 214, in _de_normalize
    broadcast_fn = self._get_broadcast_fn(x)
  File "/Users/kristian/anaconda3/envs/glow-flow/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/batch_normalization.py", line 188, in _get_broadcast_fn
    raise ValueError("Input must have shape known at graph construction.")
ValueError: Input must have shape known at graph construction.
```

Not sure if this is a feature or a bug. If it's a feature, then this is a feature request to make it support dynamic shapes. If it's a bug, then this is a bug report.

**Comment by srvasude** [comment]
I think https://github.com/tensorflow/probability/commit/fa98233abc2e92eb5164d47670a89f14a6c0d3cc should address this.

If not, please reopen this issue (I think this issue would be a feature request). In general there's weirdness to the BatchNorm bijector due to it using the BatchNormalization tf layer, which has some strict semantics.
