### ISSUE TITLE
MultivariateNormlDiag.sample caches sample shape unexpectedly

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#122]
python version: 3.6.5
tensorflow version: 1.10.0
tensorflow-probability version: 0.3.0

If a `MultivariateNormalDiag.sample` is called with a `sample_shape` that is dependent of a placeholder, then all the subsequent ops created from the same `MultivariateNormalDiag.sample` require the original placeholder to be fed to the graph. This occurs due to the shape being cached by the Bijector class (which is used for implementing the MultivariateNormalDiag).

Example:
```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfb = tfp.bijectors


def test_distribution_caching_with_non_fed_placeholder():
    base_distribution = tfp.distributions.MultivariateNormalDiag(
        loc=tf.zeros(2), scale_diag=tf.ones(2))

    # Construct a graph from placeholder 1, but never use it.
    x1_ph = tf.placeholder(dtype=tf.float32, shape=None, name="x1")
    y1 = base_distribution.sample(tf.shape(x1_ph)[0])
    _ = base_distribution.log_prob(y1)

    # Construct similar graph, which will be used later, for placeholder 2.
    x2_ph = tf.placeholder(dtype=tf.float32, shape=None, name="x2")
    y2 = base_distribution.sample(tf.shape(x2_ph)[0])
    prob2 = base_distribution.log_prob(y2)

    with tf.Session() as sess:
        x2_num = np.random.uniform(size=1)
        prob2_num = sess.run(prob2, feed_dict={x2_ph: x2_num})


if __name__ == '__main__':
    test_distribution_caching_with_non_fed_placeholder()
```

Results in:
```
Traceback (most recent call last):
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'x1' with dtype float
	 [[Node: x1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./breaking_example.py", line 28, in <module>
    test_distribution_caching_with_non_fed_placeholder()
  File "./breaking_example.py", line 24, in test_distribution_caching_with_non_fed_placeholder
    prob2_num = sess.run(prob2, feed_dict={x2_ph: x2_num})
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'x1' with dtype float
	 [[Node: x1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'x1', defined at:
  File "./breaking_example.py", line 28, in <module>
    test_distribution_caching_with_non_fed_placeholder()
  File "./breaking_example.py", line 13, in test_distribution_caching_with_non_fed_placeholder
    x1_ph = tf.placeholder(dtype=tf.float32, shape=None, name="x1")
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4925, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/kristian/anaconda3/envs/softlearning-ray/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'x1' with dtype float
	 [[Node: x1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by srvasude** [comment]
Verified that this is fixed by the same fix as in https://github.com/tensorflow/probability/issues/253.
