### ISSUE TITLE
[Jax substrate] Invalid type conversion when vectorizing a function returning a TFP distribution

### ISSUE THREAD

**Issue by tristandeleu** [tensorflow/probability#1271]
I am running into an issue with functions returning a TFP distribution (using the Jax substrate) and `vmap`, where the type conversion from TFP does not recognize the type (most likely because it is a `BatchTracer`). Here is a reproducing example:

```python
import jax.numpy as jnp

from jax import vmap
from tensorflow_probability.substrates.jax import distributions as tfd

def normal(mean):
    return tfd.Normal(mean, jnp.ones_like(mean))

mean = jnp.zeros((2, 3))
print(f'Using a tensor: {normal(mean)}')  # Works as expected
print(f'Using vmap: {vmap(normal)(mean)}')

# ValueError: Attempt to convert a value (<object object at 0x159ab49c0>) with an unsupported type (<class 'object'>) to a Tensor.
```

This is slightly different from [the behavior being tested](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/substrates/meta/jax_integration_test.py#L54) where the function only returns a sample from the distribution, here I want the function to return the distribution itself.

The complete log
<details>
<summary>Error logs</summary>

```
Traceback (most recent call last):
  File "tmp/test_bug_tfd.py", line 11, in <module>
    print(f'Using vmap: {vmap(normal)(mean)}')
  File "lib/python3.7/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "lib/python3.7/site-packages/jax/api.py", line 1240, in batched_fun
    ).call_wrapped(*args_flat)
  File "lib/python3.7/site-packages/jax/linear_util.py", line 179, in call_wrapped
    ans = gen.send(ans)
  File "lib/python3.7/site-packages/jax/interpreters/batching.py", line 75, in _match_axes
    out_dim_dests = out_dim_dests() if callable(out_dim_dests) else out_dim_dests
  File "lib/python3.7/site-packages/jax/api.py", line 1239, in <lambda>
    lambda: flatten_axes("vmap out_axes", out_tree(), out_axes)
  File "lib/python3.7/site-packages/jax/api_util.py", line 184, in flatten_axes
    dummy = tree_unflatten(treedef, [object()] * treedef.num_leaves)
  File "lib/python3.7/site-packages/jax/tree_util.py", line 85, in tree_unflatten
    return treedef.unflatten(leaves)
  File "lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 337, in unflatten
    return cls(**parameters)
  File "<decorator-gen-192>", line 2, in __init__
  File "lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 298, in wrapped_init
    default_init(self_, *args, **kwargs)
  File "lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/normal.py", line 141, in __init__
    loc, dtype=dtype, name='loc')
  File "lib/python3.7/site-packages/tensorflow_probability/substrates/jax/internal/tensor_util.py", line 123, in convert_nonref_to_tensor
    value, dtype=dtype, dtype_hint=dtype_hint, name=name)
  File "lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/_utils.py", line 67, in wrap
    return new_fn(*args, **kwargs)
  File "lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 165, in _convert_to_tensor
    ret = conversion_func(value, dtype=dtype)
  File "lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 217, in _default_convert_to_tensor
    inferred_dtype = _infer_dtype(value, np.float32)
  File "lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 195, in _infer_dtype
    value, type(value)))
ValueError: Attempt to convert a value (<object object at 0x159ab49c0>) with an unsupported type (<class 'object'>) to a Tensor.
```

</details>

My environment:
```
jax                    0.2.10
jaxlib                 0.1.62
tensorflow             2.4.1
tensorflow-probability 0.12.1
```

**Comment by davmre** [comment]
As I understand it this is unfortunately an inherent limitation of vmap's API: vmapped functions must return arrays (or 'Tensors' in TF/TFP lingo) or structures of arrays; they can't return Distributions or other nontrivial objects.

A partial workaround is that you can return a dictionary containing the raw parameters (`return dist.parameters`), and then reconstructing the distribution from those parameters outside the vmap (`tfd.Normal(**vmap(f, args))`). It's possible that we'll add utilities to TFP at some point to make this process smoother. I believe a fundamental solution would require changes to JAX for vmap to accept hooks that automate this sort of unpacking/packing.

(TensorFlow's `tf.vectorized_map` actually does support such hooks, for what it's worth, though TFP Distributions aren't yet fully linked in with them).

**Comment by tristandeleu** [comment]
Thanks a lot for the quick reply!

I thought it was possible to return the `Distribution` object directly since it is [registered as a pytree node](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/distribution.py#L323-L350), so that from the perspective of Jax it would be just another nested structure of arrays. But that's probably just half of the solution, and how to handle the `batch_shape` would be the real challenge that requires these hooks.

For now the solution that returns the raw parameters would be good enough for my current project (I can even get the `vmap` inside the function itself for that matter, I don't need that much flexibility). Thanks!

I'm also curious to hear @mattjj's thoughts (sorry for disturbing) about adding these hooks to `vmap`.

**Comment by brianwa84** [comment]
I think it's a bit more subtle, as the objects are probably sentinels or something.

i.e. we get through things fine when the init args are tracers. but when they become opaque blobs, we raise.

```
!pip install -Uq tfp-nightly[jax]
import jax.numpy as jnp

from jax import vmap
from tensorflow_probability.substrates.jax import distributions as tfd

class MyNormal(tfd.Normal):
  def __init__(self, loc, scale, **kwargs):
    print('loc=', loc, '\nscale=', scale, '\n')
    super().__init__(loc=loc, scale=scale, **kwargs)

def normal(mean):
  return MyNormal(mean, jnp.ones_like(mean))

mean = jnp.zeros((2, 3))
print(f'Using a tensor: {normal(mean)}')  # Works as expected
print(f'Using vmap: {vmap(normal)(mean)}')
```

**Comment by brianwa84** [comment]
@sharadmv any idea what these objects are?

**Comment by sharadmv** [comment]
This is due to `vmap` probing Pytrees using `object()`s as sentinels (see the logic in JAX [here](https://github.com/google/jax/blob/0a84db59ede918f1735196ed89cedaa62cb123d9/jax/api_util.py#L184)), not due to `BatchTracers` as far as I know. JAX assumes Pytree nodes are just containers and have no logic in their constructors (so they can pass whatever they want in place of arrays). In this case, we call `convert_to_tensor` (`jnp.array`) on these `object`s which causes the error. 

In past discussions with the JAX team, they were open to fixes to this issue in JAX itself. Alternatively, I've used "lazy" distributions up to this point i.e. distributions that store `args` and `kwargs` in their constructor and instantiate when a member is accessed. This avoids the `convert_to_tensor` call. For example, here is [some old Oryx code](https://github.com/tensorflow/probability/blob/1850549427f01fcdfba05746e37dc5f49f3553b7/spinoffs/oryx/oryx/distributions/distribution_extensions.py) that wraps TFP distributions. Unfortunately, Oryx no longer has lazy distributions, so a fix in TFP or JAX would be preferable.
