### ISSUE TITLE
Error with seaborn in examples/bayesian_neural_network.py (2)

### ISSUE THREAD

**Issue by gregorystrubel** [tensorflow/probability#1408]
Probably the same problem than #1209 (Error with seaborn in examples/bayesian_neural_network.py) : 

 - Without seaborn installed : no probem
 - With seaborn installed : a problem when calling seaborn functions on tensorflow tensors.

The error is not strictly the same, but I suspect this is due to that the version of seaborn and tensorflow are not strictly identical.

In my installation:
 - seaborn==0.11.2
 - tensorflow==2.6.0
 - tensorflow-estimator==2.6.0
 - tensorflow-probability==0.13.0
 
 Error:
  ... Running monte carlo inference
79/79 [==============================] - 6s 66ms/step
79/79 [==============================] - 5s 68ms/step
79/79 [==============================] - 5s 66ms/step
 ... Held-out nats: -8.628
saved /tmp/bayesian_neural_network/epoch0_step00399_weights.png
Traceback (most recent call last):
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/_core.py", line 1479, in categorical_order
    order = vector.cat.categories
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 401, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'cat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/_core.py", line 1483, in categorical_order
    order = vector.unique()
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 401, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'unique'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bayesian_neural_network.py", line 366, in <module>
    app.run(main)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "bayesian_neural_network.py", line 356, in main
    plot_heldout_prediction(heldout_seq.images, probs,
  File "bayesian_neural_network.py", line 150, in plot_heldout_prediction
    sns.barplot(np.arange(10), prob_sample[i, :], alpha=0.1, ax=ax)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/categorical.py", line 3182, in barplot
    plotter = _BarPlotter(x, y, hue, data, order, hue_order,
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/categorical.py", line 1584, in __init__
    self.establish_variables(x, y, hue, data, orient,
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/categorical.py", line 203, in establish_variables
    group_names = categorical_order(groups, order)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/seaborn/_core.py", line 1485, in categorical_order
    order = pd.unique(vector)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/pandas/core/algorithms.py", line 432, in unique
    uniques = _reconstruct_data(uniques, original.dtype, original)
  File "/Users/greg/.local/share/virtualenvs/tensorflow_probability-Uf6QUtgU/lib/python3.8/site-packages/pandas/core/algorithms.py", line 205, in _reconstruct_data
    cls = dtype.construct_array_type()
AttributeError: 'DType' object has no attribute 'construct_array_type'

**Comment by gregorystrubel** [comment]
For information, I am on macOS with environment installed by pipenv

**Comment by emilyfertig** [comment]
Hi @gregorystrubel -- this should be fixed at head (by 09bcb282450bab8b8860b89385aeee1feaeaeb5d) and in tomorrow's `tfp-nightly` pip package. (Sorry, I saw your PR right after I submitted that -- thank you for sending it, and our fixes are about the same.) I'll close this, and please reopen if you continue to see issues with it.

**Comment by gregorystrubel** [comment]
Hi @emilyfertig. I'm just glad that someone work on the project. So thanks to you.
