### ISSUE TITLE
Bug when repeatedly indexing a distribution

### ISSUE THREAD

**Issue by hosford42** [tensorflow/probability#1487]
How to reproduce:

```
dist = Normal(loc=[[0.0, 0.0]], scale=[[1.0, 1.0]])

dist[0, 1]  # Works fine

dist_0 = dist[0]

dist_0[0]  # Works fine
dist_0[1]  # Throws an exception
```

Here's the full traceback:

```
2022-01-04 13:38:26.466790: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-0112e39df1a3>", line 1, in <module>
    dist_0[1]
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py", line 881, in __getitem__
    return slicing.batch_slice(self, {}, slices)
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 217, in batch_slice
    batch_object = _apply_slice_sequence(
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 179, in _apply_slice_sequence
    batch_object = _apply_single_step(
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 168, in _apply_single_step
    override_dict = _slice_params_to_dict(
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 153, in _slice_params_to_dict
    return batch_shape_lib.map_fn_over_parameters_with_event_ndims(
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/batch_shape_lib.py", line 361, in map_fn_over_parameters_with_event_ndims
    results[param_name] = nest.map_structure_up_to(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 1376, in map_structure_up_to
    return map_structure_with_tuple_paths_up_to(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 1474, in map_structure_with_tuple_paths_up_to
    results = [
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 1475, in <listcomp>
    func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 1378, in <lambda>
    lambda _, *values: func(*values),  # Discards the path arg.
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 110, in _slice_single_param
    param_slices = _sanitize_slices(slices,
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/slicing.py", line 66, in _sanitize_slices
    is_broadcast = intended_shape[idx] > deficient_shape[idx]
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/
```

It looks like the slice is inheriting the shape constraints of the original distribution instead of removing the indexed dimension.

**Comment by csuter** [comment]
I think your batch shape is [1, 2] not [2].

Try `dist = Normal(loc=[0.0, 0.0], scale=[1.0, 1.0])`

or

`dist[0, 0]` and `dist[0, 1]`.

I think these should all work.

**Comment by jburnim** [comment]
Thanks for the bug report!

We have a fix for the issue, which should be committed and in tfp-nightly in the next day or two.

**Comment by jburnim** [comment]
Fixed by https://github.com/tensorflow/probability/commit/04787fc7086e8f630007df14f105f8b7c45b2761 .
