### ISSUE TITLE
Small bug in bfgs_minimize: 'initial_inv_hessian_estimate' should be named 'initial_inv_hessian'

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/probability#150]
I just stumbled over the following problem:
```python
> bfgs_res = tfp.optimizer.bfgs_minimize(value_and_grad_fn, param_vec, initial_inverse_hessian_estimate=hess)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-64-6c56697f62fc>", line 1, in <module>
    bfgs_res = tfp.optimizer.bfgs_minimize(value_and_grad_fn, param_vec, initial_inverse_hessian_estimate=hess)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/optimizer/bfgs.py", line 277, in minimize
    inverse_hessian_estimate=initial_inv_hessian)
UnboundLocalError: local variable 'initial_inv_hessian' referenced before assignment
```

Cause:
```python
    if initial_inverse_hessian_estimate is None:
      [...]
      initial_inv_hessian = ...
```
Otherwise `initial_inv_hessian` will not be defined.

I think this is a simple typo, `initial_inverse_hessian_estimate` should be renamed to `initial_inv_hessian`.

**Comment by saxena-ashish-g** [comment]
Thanks for catching that! I will add a fix and a test (which should have been there in the first place to test this argument).

**Comment by saxena-ashish-g** [comment]
This is now fixed after this [commit](https://github.com/tensorflow/probability/commit/ae6282b5fc56d5270b58f77f2115c6a4cc15bc0f).

Thanks again for catching this!
