### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Sission** [tensorflow/probability#157]
Hey everyone. 
I am just new here and start to ML and tensorflow. I am not good at python.
I tried to run this programming and there is an error.
Anyone can help me?

Environment: Win/Pycharm

E:\Anaconda\envs\tensorflow\python.exe "E:/Pycharm/PyCharm 2018.1.4/PythonFile/VAE.py"
Traceback (most recent call last):
  File "E:/Pycharm/PyCharm 2018.1.4/PythonFile/VAE.py", line 484, in <module>
    tf.app.run()
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "E:/Pycharm/PyCharm 2018.1.4/PythonFile/VAE.py", line 460, in main
    tf.gfile.MakeDirs(FLAGS.model_dir)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 379, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: /tmp\vae; No such file or directory

Process finished with exit code 1

**Comment by Sission** [comment]
Btw, I tried to do the vae example

**Comment by sadatnfs** [comment]
@Sission `/tmp` isn't available in a Windows setup (which is what it looks like you have), so you'd want to change all the reference to `/tmp` to some other temporary directory (with forward slashes of course).
