### ISSUE TITLE
AttributeError: module 'tree' has no attribute 'assert_same_structure'

### ISSUE THREAD

**Issue by flowpatternguy** [tensorflow/probability#1653]
Error when attempting to import tensorflow_probability in IDLE shell. There doesn't appear to be any issues when importing tensorflow_probability into the command prompt.

This is the traceback.

```
Traceback (most recent call last):
  File "C:/Users/2130943.IKB/OneDrive - Brunel University London/16. Data/Second Paper Flow Pattern Data/12. Combined Data/BNN_wine_training.py", line 8, in <module>
    import tensorflow_probability as tfp
  File "C:\Python3911\lib\site-packages\tensorflow_probability\__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "C:\Python3911\lib\site-packages\tensorflow_probability\substrates\__init__.py", line 21, in <module>
    from tensorflow_probability.python.internal import all_util
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\__init__.py", line 142, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 61, in __dir__
    module = self._load()
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Python3911\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\experimental\__init__.py", line 35, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\experimental\bijectors\__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\bijectors\__init__.py", line 23, in <module>
    from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\bijectors\absolute_value.py", line 23, in <module>
    from tensorflow_probability.python.bijectors import bijector
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py", line 30, in <module>
    from tensorflow_probability.python.internal import batch_shape_lib
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\batch_shape_lib.py", line 23, in <module>
    from tensorflow_probability.python.internal import prefer_static as ps
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\prefer_static.py", line 30, in <module>
    from tensorflow_probability.python.internal.backend import numpy as nptf
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\__init__.py", line 22, in <module>
    from tensorflow_probability.python.internal.backend.numpy import bitwise
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\bitwise.py", line 23, in <module>
    from tensorflow_probability.python.internal.backend.numpy import _utils as utils
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\_utils.py", line 26, in <module>
    from tensorflow_probability.python.internal.backend.numpy import nest
  File "C:\Python3911\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\nest.py", line 72, in <module>
    assert_same_structure = dm_tree.assert_same_structure
AttributeError: module 'tree' has no attribute 'assert_same_structure'
```

I have updated the dm-tree, tried alternative versions of tensorflow_probability. Is there anything else I can try. Rather new to Python so any help would be greatly appreciated.

**Comment by csuter** [comment]
What versions do you have installed? can you run `pip list`?

**Comment by flowpatternguy** [comment]
this is the list

absl-py                      1.3.0
astunparse                   1.6.3
cachetools                   5.2.0
certifi                      2022.9.24
charset-normalizer           2.1.1
cloudpickle                  2.2.0
colorama                     0.4.6
decorator                    5.1.1
dill                         0.3.6
dm-tree                      0.1.7
et-xmlfile                   1.1.0
etils                        0.9.0
flatbuffers                  22.10.26
gast                         0.4.0
google-auth                  2.14.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.56.4
grpcio                       1.50.0
h5py                         3.7.0
idna                         3.4
importlib-metadata           5.0.0
importlib-resources          5.10.0
jax                          0.3.25
keras                        2.10.0
keras-nightly                2.12.0.dev2022111508
Keras-Preprocessing          1.1.2
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
numpy                        1.23.4
oauthlib                     3.2.2
openpyxl                     3.0.10
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.5.1
pip                          22.3.1
promise                      2.3
protobuf                     3.19.6
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
python-dateutil              2.8.2
pytz                         2022.6
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scipy                        1.9.3
setuptools                   58.1.0
six                          1.16.0
tb-nightly                   2.11.0a20221109
tensorboard                  2.10.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.10.0
tensorflow-datasets          4.7.0
tensorflow-estimator         2.10.0
tensorflow-io-gcs-filesystem 0.27.0
tensorflow-metadata          1.11.0
tensorflow-probability       0.14.1
termcolor                    2.1.0
tf-estimator-nightly         2.12.0.dev2022111509
tf-nightly                   2.12.0.dev20221115
tf_nightly_intel             2.12.0.dev20221115
toml                         0.10.2
tqdm                         4.64.1
typing_extensions            4.4.0
urllib3                      1.26.12
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
zipp                         3.10.0

thank you

**Comment by csuter** [comment]
Thanks. Looks like you have a stable (as opposed to nightly) TFP version, but it's several versions old (0.14.1, but we're now on 0.18).

You also have tf-nightly installed alongside tensorflow (stable), and the stable version is a lot more recent than the corresponding TFP version.

Things will generally break under such conditions -- it's important to have only the versions you need, and that they be mutually consistent.

You can try manually uninstalling and reinstalling TF and TFP versions, to get them in sync, but TF installs various other things like estimator and tensorboard so that's a bit tedious/error prone. If it were me I'd delete the install env and start over from scratch. Install a consistent TFP and TF version -- either nightly of each, or find your preferred TFP version in our [release list](https://github.com/tensorflow/probability/releases/) and install the version of TF that the release notes declare they've been tested with.

Give that a try and see if your script runs?

**Comment by flowpatternguy** [comment]
I am still getting the same error. This is my setup section of the script (nothing crazy) just to ensure I'm not doing anything particularly silly as I am new to Python.

Script:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds
import tensorflow_probability as tfp

This is the traceback:

Traceback (most recent call last):
  File "C:\Users\2130943.IKB\OneDrive - Brunel University London\22. Python Code\BNN Wine Category Example.py", line 6, in <module>
    import tensorflow_probability as tfp
  File "C:\Python310\lib\site-packages\tensorflow_probability\__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "C:\Python310\lib\site-packages\tensorflow_probability\substrates\__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 40, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\experimental\__init__.py", line 31, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\experimental\bijectors\__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\bijectors\__init__.py", line 19, in <module>
    from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\bijectors\absolute_value.py", line 19, in <module>
    from tensorflow_probability.python.bijectors import bijector
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py", line 26, in <module>
    from tensorflow_probability.python.internal import batch_shape_lib
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\batch_shape_lib.py", line 23, in <module>
    from tensorflow_probability.python.internal import prefer_static as ps
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\prefer_static.py", line 26, in <module>
    from tensorflow_probability.python.internal.backend import numpy as nptf
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\__init__.py", line 18, in <module>
    from tensorflow_probability.python.internal.backend.numpy import bitwise
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\bitwise.py", line 19, in <module>
    from tensorflow_probability.python.internal.backend.numpy import _utils as utils
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\_utils.py", line 22, in <module>
    from tensorflow_probability.python.internal.backend.numpy import nest
  File "C:\Python310\lib\site-packages\tensorflow_probability\python\internal\backend\numpy\nest.py", line 68, in <module>
    assert_same_structure = dm_tree.assert_same_structure
AttributeError: module 'tree' has no attribute 'assert_same_structure'

And finally, these are the versions I have installed now:
absl-py                      1.3.0
astunparse                   1.6.3
cachetools                   5.2.0
certifi                      2022.9.24
charset-normalizer           2.1.1
cloudpickle                  2.2.0
colorama                     0.4.6
decorator                    5.1.1
dill                         0.3.6
dm-tree                      0.1.7
et-xmlfile                   1.1.0
etils                        0.9.0
flatbuffers                  1.12
gast                         0.4.0
google-auth                  2.14.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.57.0
grpcio                       1.50.0
h5py                         3.7.0
idna                         3.4
importlib-resources          5.10.0
jax                          0.3.13
keras                        2.9.0
Keras-Preprocessing          1.1.2
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
numpy                        1.23.4
oauthlib                     3.2.2
openpyxl                     3.0.10
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.5.1
pip                          22.3.1
promise                      2.3
protobuf                     3.19.6
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
python-dateutil              2.8.2
pytz                         2022.6
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scipy                        1.9.3
setuptools                   58.1.0
six                          1.16.0
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.1
tensorflow-datasets          4.7.0
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.27.0
tensorflow-metadata          1.11.0
tensorflow-probability       0.17.0
termcolor                    2.1.0
toml                         0.10.2
tqdm                         4.64.1
typing_extensions            4.4.0
urllib3                      1.26.12
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
zipp                         3.10.0

Really appreciate the help.

**Comment by flowpatternguy** [comment]
Okay, for some reason when I changed my script round to 

import tensorflow_probability as tfp
import tensorflow_datasets as tfds
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

it now works. Which is fantastic news, but if anyone knows why it would help with my understanding.

**Comment by csuter** [comment]
Strange, I tried installing the various packages at the same versions in a clean virtualenv and I do not get the error you got. I have no theory for why the import order should matter. I am on linux, though, not windows; I don't know if that could make a difference.

**Comment by ColCarroll** [comment]
python environment management can be annoying -- I'm not familiar with Windows, but inside the IDLE session, 

```python
import sys
print(sys.executable)
```

will tell you which python binary you're running. It will be something like `/Users/flowpatternguy/miniconda3/bin/python`. Then 

```
/Users/flowpatternguy/miniconda3/bin/python -m pip list
```

will list the packages associated with the python binary you're actually running.
