### ISSUE TITLE
Import error on tfp.distributions.internal for custom build

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/probability#175]
I'm getting this import error when I try to built and import TFP. I think we'd need to add something to one of init files eh?

```
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/distributions/distribution.py:265: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprec
ated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bernoulli.py:169: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b467d92c1fe3> in <module>
----> 1 import tensorflow_probability

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/__init__.py in <module>
     19
     20 # from tensorflow_probability.google import staging  # DisableOnExport
---> 21 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     22 from tensorflow_probability.python.version import __version__

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py in <module>
     20
     21 from tensorflow_probability.python import bijectors
---> 22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2
     24 from tensorflow_probability.python import glm

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py in <module>
     46 from tensorflow_probability.python.distributions.half_normal import HalfNormal
     47 from tensorflow_probability.python.distributions.independent import Independent
---> 48 from tensorflow_probability.python.distributions.internal.moving_stats import assign_log_moving_mean_exp
     49 from tensorflow_probability.python.distributions.internal.moving_stats import assign_moving_mean_variance
     50 from tensorflow_probability.python.distributions.internal.moving_stats import moving_mean_variance

ModuleNotFoundError: No module named 'tensorflow_probability.python.distributions.internal'
```

**Comment by brianwa84** [comment]
Can you add some empty `__init__.py` files in the directories in question,
and send a PR if that fixes the problem for you?

**Comment by sadatnfs** [comment]
Hmm weird thing is that all of those subfolders (including `distributions/internal`) already has init files.

**Comment by csuter** [comment]
Hi @sadatnfs -- can you share the list of versions of tensorflow and tensorflow_probability that you have installed? Also, what exact command was invoked to conjure the above error message (eg, running a script from inside/outside a clone of the TFP repo? running with a virtualenv?)

**Comment by sadatnfs** [comment]
@csuter here is the command I used to be able to run to completion to build TFP. I have always stuck with the master branch of both TF and TFP at the latest commit.

```docker 
cd /opt && git clone https://github.com/tensorflow/probability.git && \
    cd /opt/probability && \
    echo "" >> /opt/probability/tensorflow_probability/python/sts/internal/__init__.py && \
    bazel build \
    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    --copt=-mavx --copt=-msse2 --copt=-msse3 --copt=-msse4.1 --copt=-msse4.2 \
    --copt=-O3 --copt=-mfpmath=both \
    --copt="-DMKL_LP64" \
    --copt="-fPIC" \
    --linkopt="-lmkl_gf_lp64" \
    --linkopt="-lmkl_gnu_thread" \
    --linkopt="-dl" \
    --linkopt="-lpthread" \
    --linkopt="-lmkl_core" \
    --linkopt="-lm" \
    --linkopt="-lmkl_rt" \
    --linkopt="-lmkldnn" \
    :pip_pkg && \
    PKGDIR=$(mktemp -d) && \
    ./bazel-bin/pip_pkg $PKGDIR && \
    pip install --no-deps $PKGDIR/*.whl && \
    cd /opt && rm -rf /opt/probability /tmp/* && \
    python -c "import tensorflow_probability"
```

**Comment by csuter** [comment]
I am unable to repro this :(

Any other guesses about what could be different in our setups? I have bazel version 0.18.0. I also tried syncing my git clone to right before 73cbfa5, since that was the most recent change I found that touched moving_stats refs in imports/BUILD rules. Everything seems to work fine for me in all cases.

**Comment by sadatnfs** [comment]
Soooo as of right now from a build I did overnight, I actually was able to build through all good with the latest Bazel, TF and TFP... GG

**Comment by sadatnfs** [comment]
So it looks like here's the current issue I'm getting on the import:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py", line 48, in <module>
    from tensorflow_probability.python.distributions.internal.moving_stats import assign_log_moving_mean_exp
ModuleNotFoundError: No module named 'tensorflow_probability.python.distributions.internal'```

One interesting thing is: when I `ls` into the distributions folder that's installed, I see no `internal` folder:
```root@192ae56940a5:/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/distributions# ls
autoregressive.py                        dirichlet.py                          __init__.py             multinomial.py                  poisson.py                     vector_diffeomixture.py
batch_reshape.py                         distribution.py                       inverse_gamma.py        mvn_diag_plus_low_rank.py       __pycache__                    vector_exponential_diag.py
bernoulli.py                             exponential.py                        inverse_gaussian.py     mvn_diag.py                     quantized_distribution.py      vector_exponential_linear_operator.py
beta.py                                  gamma_gamma.py                        kullback_leibler.py     mvn_full_covariance.py          relaxed_bernoulli.py           vector_laplace_diag.py
binomial.py                              gamma.py                              kumaraswamy.py          mvn_linear_operator.py          relaxed_onehot_categorical.py  vector_laplace_linear_operator.py
categorical.py                           gaussian_process.py                   laplace.py              mvn_tril.py                     sample_stats.py                vector_sinh_arcsinh_diag.py```

**Comment by csuter** [comment]
yeah, so that's probably the problem :)

usually this is because the BUILD rules are wonky. it's weird that it isn't happening in my build. I'll take a closer look at a few things.

**Comment by csuter** [comment]
are you certain that the pip install is actually overwriting the existing install in /opt/conda? are you using pip install --upgrade to install? or pip uninstall tf-nightly first?

i see a lot of issues with imports coming from users using conda. i don't know much about it. is there something it could be doing that's weird?

**Comment by csuter** [comment]
> When I built TF, I pip uninstalled all other instances of TF, so that I can have a single, clean TF.

what about TFP?

**Comment by csuter** [comment]
the following sequence works fine for me in python2.7, python3.5 and python3.6 (i.e., import works and site-packages subdirectory contains distributions/internal as expected):

```
mkdir /tmp/ve
cd /tmp/ve
virtualenv -p $python_version .   # set python_version to one of python2, python3.5, python3.6
. bin/activate
pip install tf-nightly
git clone https://github.com/tensorflow/probability
cd probability
bazel build :pip_pkg
./bazel-bin/pip_pkg ./wheels
pip install ./wheels/*.whl
python -c 'import tensorflow_probability'
```

so i am skeptical that the BUILD rules are actually problematic

**Comment by sadatnfs** [comment]
I tried that, still failing.

So one thing I tried: I copied out the `internal` folder from the cloned repo into the site-packages subfolder, because `internal` was not there at all. Then I tried to import and I get this error:

```
<ipython-input-1-41494c8c96ff> in <module>
----> 1 import tensorflow_probability as tfp

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/__init__.py in <module>
     19
     20 # from tensorflow_probability.google import staging  # DisableOnExport
---> 21 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     22 from tensorflow_probability.python.version import __version__

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py in <module>
     28 from tensorflow_probability.python import monte_carlo
     29 from tensorflow_probability.python import optimizer
---> 30 from tensorflow_probability.python import positive_semidefinite_kernels
     31 from tensorflow_probability.python import sts
     32 from tensorflow_probability.python import trainable_distributions

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/positive_semidefinite_kernels/__init__.py in <module>
     19 from __future__ import print_function
     20
---> 21 from tensorflow_probability.python.positive_semidefinite_kernels.exp_sin_squared import ExpSinSquared
     22 from tensorflow_probability.python.positive_semidefinite_kernels.exponentiated_quadratic import ExponentiatedQuadratic
     23 from tensorflow_probability.python.positive_semidefinite_kernels.matern import MaternFiveHalves

/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/positive_semidefinite_kernels/exp_sin_squared.py in <module>
     23 from tensorflow_probability.python.internal import dtype_util
     24 from tensorflow_probability.python.positive_semidefinite_kernels import positive_semidefinite_kernel as psd_kernel
---> 25 from tensorflow_probability.python.positive_semidefinite_kernels.internal import util
     26
     27 __all__ = [

ModuleNotFoundError: No module named 'tensorflow_probability.python.positive_semidefinite_kernels.internal'
```

Would there be a reason why the build is dropping the `internal` named folders?

**Comment by sadatnfs** [comment]
@csuter could you try navigating out of the cloned folder (and maybe removing the clone as well) and then try to import tfp?

**Comment by csuter** [comment]
Ahh, that was the problem (I was still cd'ed into the repo dir). Ok, this is a problem with build files and i know how to fix. Will follow up shortly. Thanks for helping to debug and repro!

**Comment by sadatnfs** [comment]
Hah yeah I was also able to magically import (and even commented and removed my comment) when I was in the cloned folder! Thanks Chris!

Yeah I was looking into the BUILD files, and I wonder if it is a simple fix as just adding the internal folder path into the `py_library`s..

**Comment by sadatnfs** [comment]
(Also, thanks a lot for your help!)

**Comment by csuter** [comment]
i think the fix will entail a couple of changes. most importantly, we need to update some internal CI tools. the problem is our pip package build/install test currently uses an ancient version of Bazel, which actually created these missing deps and __init__ files automatically. Newer versions don't have this behavior (which is good, IMO, since it's more explicit and less magic). So our test environment is actually unrealistic (no one uses such old bazel versions in the wild). It's a shared env and so updating means doing some extra plumbing on our own...I will be looking into it ASAP so we stop being bitten by this issue :)

**Comment by sadatnfs** [comment]
I can confirm that the build and import is working perfectly now! Thanks @csuter for the quick fix!!

**Comment by csuter** [comment]
Excellent. We are also implementing the fixes to our test setup presently, which will prevent these oversights from sneaking through.
