### ISSUE TITLE
JAX PowerSpherical Distribution Sampling Error

### ISSUE THREAD

**Issue by smorad** [tensorflow/probability#1838]
I am unable to sample from the `PowerSpherical` distribution using `jax`. Please see the below code:

```python

from tensorflow_probability.substrates import jax as tfp
import jax.numpy as jnp
import jax

# Test sampling from normal, as sanity check
dist0 = tfp.distributions.Normal(loc=jnp.zeros(10, dtype=jnp.float32), scale=jnp.ones(10, dtype=jnp.float32))
dist0.sample(seed=jax.random.PRNGKey(0))

dist1 = tfp.distributions.PowerSpherical(mean_direction=jnp.ones(10, dtype=jnp.float32), concentration=jnp.array(1.0))
dist1.sample(seed=jax.random.PRNGKey(0))
```

The above code produces the following stack trace:

```python
Traceback (most recent call last):
  File "/Users/smorad/code/gcgvf/test.py", line 9, in <module>
    dist1.sample(seed=jax.random.PRNGKey(0))
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 1205, in sample
    return self._call_sample_n(sample_shape, seed, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 1182, in _call_sample_n
    samples = self._sample_n(
              ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/distributions/power_spherical.py", line 282, in _sample_n
    beta_seed, uniform_seed = samplers.split_seed(seed, salt='power_spherical')
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/internal/samplers.py", line 222, in split_seed
    seed = sanitize_seed(seed, salt=salt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/internal/samplers.py", line 144, in sanitize_seed
    seed = fold_in(seed, salt)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/gcgvf/lib/python3.12/site-packages/tensorflow_probability/substrates/jax/internal/samplers.py", line 186, in fold_in
    seed, jnp.asarray(salt & np.uint32(2**32 - 1), dtype=SEED_DTYPE))
                      ~~~~~^~~~~~~~~~~~~~~~~~~~~~
OverflowError: Python int too large to convert to C long
```

I am running this code on an M1 mac with python 3.12.5, and the following software versions
```bash
jax                    0.4.31
jaxlib                 0.4.31
tensorflow-probability 0.24.0
```

**Comment by SiegeLordEx** [comment]
This was fixed in https://github.com/tensorflow/probability/commit/8a5daf0224436fee1d7cd8e18382891ee92db3c4. The fix is available in `tfp_nightly` package, and also a future stable release, if it ever happens.
