### ISSUE TITLE
Tensorflow 1.12.0 linear_operator_addition library location change

### ISSUE THREAD

**Issue by myunusseker** [tensorflow/probability#215]
Using Tensorflow Probability with Tensorflow 1.12.0 , Error is:
`Traceback (most recent call last):
  File "cnp.py", line 3, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/distributions/__init__.py", line 77, in <module>
    from tensorflow_probability.python.distributions.vector_diffeomixture import quadrature_scheme_softmaxnormal_gauss_hermite
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/distributions/vector_diffeomixture.py", line 25, in <module>
    from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib
ImportError: No module named linalg.python.ops`

So,
` from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib`
in `/tensorflow_probability/python/distributions/vector_diffeomixture.py`
should be changed to
`from tensorflow.python.ops.linalg import linear_operator_addition as linop_add_lib`

**Comment by brianwa84** [comment]
Please give tfp 0.5rc1 a try.
