### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by karimbk** [tensorflow/probability#270]
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-0dbca5f4cfb9> in <module>()
----> 1 from keras.models import Sequential
      2 from keras.layers import Dense
      3 from keras.wrappers.scikit_learn import KerasClassifier
      4 from keras.callbacks import Callback
      5 from keras.callbacks import TensorBoard

~/anaconda/lib/python3.6/site-packages/keras/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

~/anaconda/lib/python3.6/site-packages/keras/utils/conv_utils.py in <module>()
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

~/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py in <module>()
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

~/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages

~/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     28 
     29 # pylint: disable=g-bad-import-order
---> 30 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     31 
     32 try:

~/anaconda/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     86 # Bring in subpackages.
     87 from tensorflow.python import data
---> 88 from tensorflow.python import keras
     89 from tensorflow.python.feature_column import feature_column_lib as feature_column
     90 from tensorflow.python.layers import layers

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py in <module>()
     22 from __future__ import print_function
     23 
---> 24 from tensorflow.python.keras import activations
     25 from tensorflow.python.keras import applications
     26 from tensorflow.python.keras import backend

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/activations/__init__.py in <module>()
     20 
     21 # Activation functions.
---> 22 from tensorflow.python.keras._impl.keras.activations import elu
     23 from tensorflow.python.keras._impl.keras.activations import hard_sigmoid
     24 from tensorflow.python.keras._impl.keras.activations import linear

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 from tensorflow.python.keras._impl.keras import activations
     22 from tensorflow.python.keras._impl.keras import applications
     23 from tensorflow.python.keras._impl.keras import backend

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py in <module>()
     21 import six
     22 
---> 23 from tensorflow.python.keras._impl.keras import backend as K
     24 from tensorflow.python.keras._impl.keras.utils.generic_utils import deserialize_keras_object
     25 from tensorflow.python.layers.base import Layer

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py in <module>()
     36 from tensorflow.python.framework import sparse_tensor
     37 from tensorflow.python.framework import tensor_util
---> 38 from tensorflow.python.layers import base as tf_base_layers
     39 from tensorflow.python.ops import array_ops
     40 from tensorflow.python.ops import clip_ops

~/anaconda/lib/python3.6/site-packages/tensorflow/python/layers/base.py in <module>()
     23 from tensorflow.python.framework import dtypes
     24 from tensorflow.python.framework import ops
---> 25 from tensorflow.python.keras.engine import base_layer
     26 from tensorflow.python.ops import variable_scope as vs
     27 from tensorflow.python.ops import variables as tf_variables

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/engine/__init__.py in <module>()
     21 # TODO(fchollet): Remove hourglass imports once external code is done importing
     22 # non-public APIs.
---> 23 from tensorflow.python.keras.engine.base_layer import InputSpec
     24 from tensorflow.python.keras.engine.base_layer import Layer
     25 from tensorflow.python.keras.engine.input_layer import Input

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in <module>()
     33 from tensorflow.python.framework import tensor_shape
     34 from tensorflow.python.framework import tensor_util
---> 35 from tensorflow.python.keras import backend
     36 from tensorflow.python.keras import constraints
     37 from tensorflow.python.keras import initializers

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/backend/__init__.py in <module>()
     20 
     21 # pylint: disable=redefined-builtin
---> 22 from tensorflow.python.keras._impl.keras.backend import abs
     23 from tensorflow.python.keras._impl.keras.backend import all
     24 from tensorflow.python.keras._impl.keras.backend import any

ImportError: cannot import name 'abs'
```
This just happened when I wanted to upgrade Keras to version 2.2.3 , using "conda install keras" after it was already installed. Before I had keras 2.2.0 or something (installed in March 2018 idk which version was it exactly) Before executing the "conda install keras" today, everything was working! Now I have to work on my final thesis which have to be submitted next week, and I have this problem :( Hope someone can help!! I restarted Anaconda, and closed all terminals, and opened again, still not working and having that same error above. Should I maybe restart my computer? (Mac)

**Comment by mayou36** [comment]
To me this looks like a problem in Keras or TensorFlow and has nothing to do with TensorFlow Probability (which is the Repo you posted in).

I would create a new conda environment and do a fresh install of your packages.

If the problem persists, post the issue again in TensorFlow or Keras.

**Comment by jvdillon** [comment]
Thanks @mayou36!

**Comment by aGiant** [comment]
I had the same problem. Already tried to uninstall keras and tensorflow, then reinstall tensorflow only. But error remains almost the same:
```
  File "<stdin>", line 1, in <module>
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 82, in <module>
    from tensorflow.python import keras
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import Layer
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 34, in <module>
    from tensorflow.python.keras import backend
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
```

**Comment by mayou36** [comment]
@aGiant to me it looks to be a problem with TensorFlow and is not related to tensorflow-probability, right?

Or is there any reason why you think this is related?
