### ISSUE TITLE
Broadcasting problems in distributions.MultivariateNormalFullCovariance

### ISSUE THREAD

**Issue by bjfar** [tensorflow/probability#390]
I cannot for the life of me get broadcasting to work in the MultivariateNormalFullCovariance distribution. I am defining two tensors of mean variables, and I want to broadcast this against a fixed 2x2 covariance matrix. But nothing I am trying is working. Example below:

```
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd
import numpy as np

eta = [tf.Variable(np.zeros(20,dtype='float32'), name='eta{0}'.format(i)) for i in range(2)]

print("eta:", eta)

# Problem here?
cov = [[0.5, 0.5],[0.5,0.5]] # Nope
#cov = np.array(cov,dtype='float32') # Nope
cov = np.array(cov,dtype='float32')[np.newaxis,...] # Nope

mvn = tfd.MultivariateNormalFullCovariance(eta,cov)

# Get samples
Ntrials = 100
samples0 = mvn.sample(Ntrials)

print("samples:", samples0)

# Get pdf values for samples
p = mvn.log_prob(samples0)

print("pdf vals:", p)
print("Finished!")
```

Output:

```
eta: [<tf.Variable 'eta0:0' shape=(20,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)>, <tf.Variable 'eta1:0' shape=(20,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)>]

Traceback (most recent call last):
  File "test_tfp_bug2.py", line 15, in <module>
    mvn = tfd.MultivariateNormalFullCovariance(eta,cov)
  File "</home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/decorator.py:decorator-gen-154>", line 2, in __init__
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/distribution.py", line 269, in wrapped_init
    default_init(self_, *args, **kwargs)
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/mvn_full_covariance.py", line 188, in __init__
    name=name)
  File "</home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/decorator.py:decorator-gen-132>", line 2, in __init__
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/distribution.py", line 269, in wrapped_init
    default_init(self_, *args, **kwargs)
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/mvn_tril.py", line 217, in __init__
    name=name)
  File "</home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/decorator.py:decorator-gen-94>", line 2, in __init__
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/distribution.py", line 269, in wrapped_init
    default_init(self_, *args, **kwargs)
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/distributions/mvn_linear_operator.py", line 184, in __init__
    loc, scale)
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/tensorflow_probability/python/internal/distribution_util.py", line 323, in shapes_from_loc_and_scale
    "of 'loc' ({}).".format(event_size_, loc_event_size_))
ValueError: Event size of 'scale' (2) could not be broadcast up to that of 'loc' (20).
```

**Comment by bjfar** [comment]
Ahh ok, after discovering this notebook on how shapes work in tensorflow_probability (https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Understanding_TensorFlow_Distributions_Shapes.ipynb) I think I have made it work. In my case I needed to stack the input variables into one tensor so that I could arrange the "samples" dimension to be first:

```
all_eta = tf.stack(eta, axis=1, name='all_eta')
```
then
```
cov = [[1.0, 0.0],[0.0,1.0]]
tfd.MultivariateNormalFullCovariance(all_eta,cov)
```

works.

**Comment by brianwa84** [comment]
Yeah shapes can be tricky, but the vectorization win is worth having. :)
