### ISSUE TITLE
Feature request: Need to reshape event from scalar to vector

### ISSUE THREAD

**Issue by EliasHasle** [tensorflow/probability#451]
I am making a Cross-Validation ensemble of distribution models. Each distribution model outputs a list of independent distributions, one for each output dimension. The CV ensemble has K such submodels. I want to mix the outputs of the models according to weights that are computed per-sample (but different for training and validation), to perform cross-validation along with training and end up with an ensemble model that always queries one (or, perhaps in the future, more) submodel that is not trained on the data point in question.

This is my current best try:
```
weights = tf.expand_dims(self.get_CV_validation_weights(batch),2)
submodel_outputs = [submodel(batch) for submodel in self.submodels]
        cv_dists = [tfd.Mixture(
            cat=tfd.Categorical(probs=tf.transpose(weights,perm=[1,0,2])[:,:], allow_nan_stats=False),
            components=[tfd.TransformedDistribution(distribution=submodel_outputs[j][i], bijector=tfp.bijectors.Reshape(event_shape_in=(), event_shape_out=(-1,))) for j in range(self.cv_components)],
            allow_nan_stats=False
        ) for i in range(self.output_size)]
        return cv_dists
```

Note that the shape of weights is (cv_components, batch_size,1), so the shape of tf.transpose(weights,perm=[1,0,2])[:,:] is (batch_size, cv_components).

The batch shape of each submodel output distribution is (batch_size,) and the event shape is (), i.e. scalar. This is where it fails, because the Mixture apparently requires the components to have shape rank 2, and the Reshape operation does not convert the scalar into a length 1 vector.

```
Stack trace:
Traceback (most recent call last):
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 846, in merge_with
    self.assert_same_rank(other)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 891, in assert_same_rank
    other))
ValueError: Shapes (128, 3) and (128,) must have the same rank

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CV_Ensemble_dist_experiment.py", line 30, in <module>
    model(dummy_batch)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\sonnet\python\modules\base.py", line 396, in __call__
    return self._call(*args, **kwargs)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\sonnet\python\modules\base.py", line 418, in _call
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\sonnet\python\modules\base.py", line 226, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\elias\Dropbox (Personal)\PhD\Projects\geiranger_pilot_iir\models\CV_Ensemble.py", line 116, in _build
    ) for i in range(self.output_size)]
  File "C:\Users\elias\Dropbox (Personal)\PhD\Projects\geiranger_pilot_iir\models\CV_Ensemble.py", line 116, in <listcomp>
    ) for i in range(self.output_size)]
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_probability\python\distributions\mixture.py", line 142, in __init__
    static_batch_shape = static_batch_shape.merge_with(d.batch_shape)
  File "C:\Users\elias\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 852, in merge_with
    raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (128, 3) and (128,) are not compatible
```

**Comment by brianwa84** [comment]
One nitpick here: the shape of `tf.transpose(weights,perm=[1,0,2])[:,:]` is the same as the shape of `tf.transpose(weights,perm=[1,0,2])`. If you want to squeeze the last dim, you can use `tf.squeeze` or `tf.transpose(weights,perm=[1,0,2])[..., 0]`

**Comment by EliasHasle** [comment]
@brianwa84 That is a very valuable nitpick. Solved my particular problem. Thank you! 🥇 

I was thinking about another workaround, which would involve artificially increasing the event shape dimensions on all constituent distributions, but this solution is neater.

Still, would it be a bad idea to be able to "reshape" scalar events into single-element tensor events?

**Comment by EliasHasle** [comment]
I realized after posting that I hadn't removed the reshaping transformation, and the program still ran. Now I tested without the reshaping, and the program ran. I think that means the reshaping silently did nothing (which can't be a good thing, can it?).

**Comment by EliasHasle** [comment]
I am not certain the reshaping did nothing. It could be that its effects where just nulled out by a subsequent `reduce_mean` or something. I close this issue now, until a valid/critical use case surfaces.
