### ISSUE TITLE
Error reporting for "ValueError: Encountered `None` gradient."

### ISSUE THREAD

**Issue by matthew-mcateer** [tensorflow/probability#47]
So I have been trying to run a Monte Carlo Markov chain, with a format similar to the following,
```python
states, kernel_results = tfp.mcmc.sample_chain(
    num_results=2000,
    num_burnin_steps=1400,
    current_state=[                # Based on my undrstanding the initial states are defined here
        tf.constant(100, dtype=tf.float32, name='init_weight'),
        tf.constant([2100., 2100.], dtype=tf.float32, name='init_position'),
        tf.random_normal(shape=[2, num_inputs], mean=0.0, stddev=0.3,  # random initialization
                         dtype=tf.float32, name='init_effect_avg')
    ],
    kernel=tfp.mcmc.HamiltonianMonteCarlo( 
        target_log_prob_fn=approximate_posterior_log_prob,
        step_size=7, 
        num_leapfrog_steps=10))
```
And lately, when I've been running it, the following error arises:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-56-803fa2bc7bec> in <module>()
     12         target_log_prob_fn=approximate_posterior_log_prob,
     13         step_size=7,
---> 14         num_leapfrog_steps=10))
     15 
     16 halo_position, ellpty_avg, test_mass = states

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/sample.py in sample_chain(num_results, current_state, previous_kernel_results, kernel, num_burnin_steps, num_steps_between_results, parallel_iterations, name)
    238 
    239     if previous_kernel_results is None:
--> 240       previous_kernel_results = kernel.bootstrap_results(current_state)
    241     return tf.scan(
    242         fn=_scan_body,

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/hmc.py in bootstrap_results(self, init_state)
    367   def bootstrap_results(self, init_state):
    368     """Creates initial `previous_kernel_results` using a supplied `state`."""
--> 369     return self._impl.bootstrap_results(init_state)
    370 
    371 

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py in bootstrap_results(self, init_state)
    264         name=mcmc_util.make_name(self.name, 'mh', 'bootstrap_results'),
    265         values=[init_state]):
--> 266       pkr = self.inner_kernel.bootstrap_results(init_state)
    267       if not has_target_log_prob(pkr):
    268         raise ValueError(

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/hmc.py in bootstrap_results(self, init_state)
    507           init_target_log_prob,
    508           init_grads_target_log_prob,
--> 509       ] = mcmc_util.maybe_call_fn_and_grads(self.target_log_prob_fn, init_state)
    510       return UncalibratedHamiltonianMonteCarloKernelResults(
    511           log_acceptance_correction=tf.zeros_like(init_target_log_prob),

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/mcmc/util.py in maybe_call_fn_and_grads(fn, fn_arg_list, result, grads, check_non_none_grads, name)
    235                        'with grads.')
    236     if check_non_none_grads and any(g is None for g in grads):
--> 237       raise ValueError('Encountered `None` gradient.')
    238     return result, grads

ValueError: Encountered `None` gradient.
```
The problem is that this does not give a lot of information. I don't know which of the initial states has been erroneous (I have been trying out many different states with different shapes and initialization strategies, all of which have been leading to this same error). I also don't know whether this is just a zero gradient, if this is the result of a gradient missing entirely, if data of `dtype=None` is somehow being fed in, if this is a gradient that eventually vanishes (which makes it slightly harder to know if the usual approaches to vanishing gradients do any good). 

If there was something like reporting on the index of the initial state, that would be extremely helpful.

Is it possible that I'm just misusing TFP in this case? Should I try to find a way to manually input the gradients?

**Comment by SiegeLordEx** [comment]
Thanks for the report, we've improved the error message. In terms of your usage, it appears to be fine so the error must have been somewhere inside `approximate_posterior_log_prob`.

**Comment by arunpatro** [comment]
Hi there, I am too facing the same issue, and i am not able to solve it. My error is not in the target_log_prob_fn. 

CODE:
```python
import tensorflow as tf
tf.enable_eager_execution()
import tensorflow_probability as tfp
from tensorflow_probability import edward2 as ed
import numpy as np
from scipy.stats import multivariate_normal


tfd = tfp.distributions

x_true = multivariate_normal.rvs(cov=np.eye(4), size = 500)

def mvnmodel(data_size=1, dimension=4):
    nu = ed.Uniform(name="nu", low=tf.constant(0.), high=tf.constant(4.))
    corr_mat = ed.LKJ(name="corr", dimension=4, concentration=nu)
    sigma = ed.LogNormal(name='sigma', loc=tf.zeros([dimension]), scale=tf.ones([dimension]))
    sigma_mat = tf.diag(name="sigma_mat", diagonal=sigma)
    cov_mat = sigma_mat @ corr_mat @ sigma_mat 
    L_tril = tf.cholesky(cov_mat)
    mu = ed.MultivariateNormalTriL(name="mu", loc=tf.zeros([4]), scale_tril = L_tril)
    x = ed.MultivariateNormalTriL(name="x", loc=mu, scale_tril = L_tril, sample_shape=[data_size])
    return x

log_joint = ed.make_log_joint_fn(mvnmodel)

nu0 = np.random.uniform(0, 4)
with tf.Session() as sess:
    corr_tmp = ed.LKJ(name="corr0", dimension=4, concentration=nu0, validate_args=True)
    l_tril = tf.cholesky(corr_tmp)
    corr0, l_tril0 = sess.run([corr_tmp, l_tril])
sigma0 = np.random.lognormal(np.zeros(4), np.ones(4))
mu0 = np.random.multivariate_normal(np.zeros(4), np.eye(4))

qnu = tf.convert_to_tensor(nu0, name='qnu')
qcorr = tf.convert_to_tensor(corr0, name='qcorr')
qsigma = tf.convert_to_tensor(sigma0, name='qsigma')
qmu = tf.convert_to_tensor(mu0, name='qmu')

q_list = [qnu, qcorr, qsigma, qmu]

print('Printing\n', [qnu, qcorr, qsigma, qmu])

def target_log_prob_fn(nu, corr, sigma, mu):
    return log_joint(data_size=x_true.shape[0], 
                     dimension=x_true.shape[1], 
                     nu=qnu, 
                     corr=qcorr, 
                     sigma=qsigma, 
                     mu=qmu, 
                     x=x_true)

print(target_log_prob_fn(qnu, qcorr, qsigma, qmu)) #works

hmc_kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.01,
    num_leapfrog_steps=5)

states, kernels_results = tfp.mcmc.sample_chain(
    num_results=1000,
    current_state=[qnu, qcorr, qsigma, qmu],
    kernel=hmc_kernel,
    num_burnin_steps=0)
```


ERROR:
```python
Printing
 [<tf.Tensor: id=353, shape=(), dtype=float32, numpy=3.3430696>, <tf.Tensor: id=354, shape=(4, 4), dtype=float32, numpy=
array([[ 1.        ,  0.57910216,  0.18112545, -0.2228805 ],
       [ 0.57910216,  1.        , -0.44517764, -0.42296514],
       [ 0.18112545, -0.44517764,  1.        ,  0.4743349 ],
       [-0.2228805 , -0.42296514,  0.4743349 ,  1.        ]],
      dtype=float32)>, <tf.Tensor: id=355, shape=(4,), dtype=float64, numpy=array([5.05385036, 0.36153196, 8.35021843, 3.05508949])>, <tf.Tensor: id=356, shape=(4,), dtype=float64, numpy=array([-0.17279591,  0.68791932, -1.70513022,  1.3289289 ])>]
tf.Tensor(-12322.489, shape=(), dtype=float32)
Traceback (most recent call last):
  File "tfp-edward.py", line 70, in <module>
    num_burnin_steps=0)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 235, in sample_chain
    previous_kernel_results = kernel.bootstrap_results(current_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 518, in bootstrap_results
    kernel_results = self._impl.bootstrap_results(init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 264, in bootstrap_results
    pkr = self.inner_kernel.bootstrap_results(init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 687, in bootstrap_results
    ] = mcmc_util.maybe_call_fn_and_grads(self.target_log_prob_fn, init_state)
  File "/Users/300041738/.arun-venv3/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/util.py", line 248, in maybe_call_fn_and_grads
    '  grads: {}'.format(fn_arg_list, grads))
ValueError: Encountered `None` gradient.
  fn_arg_list: [<tf.Tensor: id=353, shape=(), dtype=float32, numpy=3.3430696>, <tf.Tensor: id=354, shape=(4, 4), dtype=float32, numpy=
array([[ 1.        ,  0.57910216,  0.18112545, -0.2228805 ],
       [ 0.57910216,  1.        , -0.44517764, -0.42296514],
       [ 0.18112545, -0.44517764,  1.        ,  0.4743349 ],
       [-0.2228805 , -0.42296514,  0.4743349 ,  1.        ]],
      dtype=float32)>, <tf.Tensor: id=355, shape=(4,), dtype=float64, numpy=array([5.05385036, 0.36153196, 8.35021843, 3.05508949])>, <tf.Tensor: id=356, shape=(4,), dtype=float64, numpy=array([-0.17279591,  0.68791932, -1.70513022,  1.3289289 ])>]
  grads: [None, None, None, None]
```

Please look at this [question](https://stackoverflow.com/q/56498469/4138044) on SO

**Comment by arunpatro** [comment]
@matthew-mcateer Please have a look. Have you solved the issue?
