### ISSUE TITLE
TypeError: Tensor is unhashable if Tensor equality is enabled

### ISSUE THREAD

**Issue by jaekookang** [tensorflow/probability#537]
Hi.

I have a problem running tensorflow_probability tutorial code as in here: [https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/TensorFlow_Distributions_Tutorial.ipynb](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/TensorFlow_Distributions_Tutorial.ipynb)

The issue occurs when I run `nd.sample()`.
```python
nd = tfd.MultivariateNormalDiag(loc=[0., 10.], scale_diag=[1., 4.])
nd.sample()
```
Error message:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/distributions/distribution.py", line 840, in sample
    return self._call_sample_n(sample_shape, seed, name, **kwargs)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py", line 391, in _call_sample_n
    y = self.bijector.forward(x, **bijector_kwargs)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 933, in forward
    return self._call_forward(x, name, **kwargs)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 904, in _call_forward
    mapping = self._lookup(x=x, kwargs=kwargs)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 1343, in _lookup
    mapping = self._from_x[x].get(subkey, mapping).merge(x=x)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 151, in __getitem__
    return super(WeakKeyDefaultDict, self).__getitem__(weak_key)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/bijector.py", line 181, in __hash__
    return hash(x)
  File "/Users/jaegukang/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 713, in __hash__
    raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```

I don't have any problem when I'm using `tfd.Normal`. It seems to me that the issue is related to the multivariate version of this function.

I'm using Python3.6, tensorflow==2.0.0rc0 and tensorflow_probability==0.7.0 on macOS Mojave.

You can replicate this on colab ([https://colab.research.google.com/drive/1cNeU3jd5MWegY9FiczUFc_bCa1KzgEaE#scrollTo=MSX_sqHkPSM0](https://colab.research.google.com/drive/1cNeU3jd5MWegY9FiczUFc_bCa1KzgEaE#scrollTo=MSX_sqHkPSM0)).

Please let me know if I missed anything.

Thank you.

**Comment by brianwa84** [comment]
For the 2.0 rc you should currently use tfp-nightly. We will have a
0.8.0rc0 ready soon, which will be out 2.0.0rc0 correspondence.

**Comment by jaekookang** [comment]
I see. I simply downgraded tf to 2.0.0b1 and it works fine. I'll try tfp-nightly as well. Thank you.

**Comment by brianwa84** [comment]
tensorflow-probability==0.8.0rc0 is now up on pypi, please feel free to
kick the tires with tensorflow==2.0.0rc0!

Brian Patton | Software Engineer | bjp@google.com
