### ISSUE TITLE
tfp import error: AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by kristofgiber** [tensorflow/probability#541]
version to reproduce:
tf-gpu 2.0.0-rc0 and tfp 0.6

import tensorflow_probability as tfp

Traceback (most recent call last):
  File "/home/pycharm_project/VAE/save_issue_reproduction.py", line 1, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/__init__.py", line 78, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/__init__.py", line 21, in <module>
    from tensorflow_probability.python import bijectors
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/__init__.py", line 46, in <module>
    from tensorflow_probability.python.bijectors.matveclu import MatvecLU
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/matveclu.py", line 24, in <module>
    from tensorflow_probability.python.math.linalg import lu_reconstruct
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/math/__init__.py", line 22, in <module>
    from tensorflow_probability.python.math.diag_jacobian import diag_jacobian
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/math/diag_jacobian.py", line 24, in <module>
    tfe = tf.contrib.eager
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by brianwa84** [comment]
To use 2.0.0rc0 you'll need tensorflow-probability==0.8.0rc0
Brian Patton | Software Engineer | bjp@google.com

**Comment by kristofgiber** [comment]
Awesome thank you!
