### ISSUE TITLE
Poisson random variable samples float instead of int, fails in hierarchical modeling as result

### ISSUE THREAD

**Issue by daniel-s-cunha** [tensorflow/probability#553]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, derived from tf example.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.4
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: v1.14.0-rc1-22-gaf24dc91b5 1.14.0 and 2.0
- **Python version**: Python 3.7.3
- **Exact command to reproduce**: I am implementing a hierarchical model, where the value of the Poisson sample is used to determine the batch size of the normal distribution. Since the Poisson sample is a float, the MCMC step function treats it as a float. This results in incorrect mathematics for MCMC to work. In general, I cannot get this code to run.  

```python
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors

rv_m = tfd.Poisson(rate=1.)
m    = rv_m.sample()

def joint_log_prob(m):
    rv_m    = tfd.Poisson(rate=1.)
    m_int   = tf.cast(m,'int32')
    rv_norm = tfd.Normal(loc=tf.zeros(m_int),scale=1.)
    return (-1.)

number_of_steps = 1000
burnin          = 0

initial_chain_state      = [m]
log_prob                 = lambda *args: joint_log_prob(*args)
[post_m], kernel_results = tfp.mcmc.sample_chain(num_results=number_of_steps,num_burnin_steps=burnin,current_state=initial_chain_state,kernel=tfp.mcmc.RandomWalkMetropolis(target_log_prob_fn=log_prob,seed=4))
```
### Source code / logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 361, in sample_chain
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 370, in trace_scan
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 359, in _body
    state = loop_fn(state, elems_array.read(i))
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 345, in _trace_scan_fn
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 286, in smart_for_loop
    parallel_iterations=parallel_iterations
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 284, in <lambda>
    body=lambda i, *args: [i + 1] + list(body_fn(*args)),
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/random_walk_metropolis.py", line 440, in one_step
    return self._impl.one_step(current_state, previous_kernel_results)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 194, in one_step
    previous_kernel_results.accepted_results)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/random_walk_metropolis.py", line 533, in one_step
    dtype=next_target_log_prob.dtype.base_dtype),
AttributeError: 'float' object has no attribute 'dtype'
```

**Comment by brianwa84** [comment]
I wonder if the problem is your return (-1.)

Try return tf.constant(-1.)?

You might also look at tfp.distributions.JointDistributionSequential.

**Comment by daniel-s-cunha** [comment]
Confirmed: returning tf.constant(-1.) no longer induces the error message.  Thank you for pointing that out.  I have updated the ticket.

This still leaves us with the issue that the Poisson samples of m are float, thus the MCMC step function is treating it as continuous and returning continuous values of m (which should be an integer).  Here are some posterior samples of m from the above code which should be an int:

``` 
array([  1.3162322 ,   2.8524532 ,   2.6844528 ,   2.6301203 ,
         3.6197033 ,   4.435177  ,   4.5485897 ,   4.381496  ,
         5.7595267 ,   7.068791  ,   5.875636  ,   7.246412  ,
         7.604823  ,   8.934201  ,   7.629205  ,   8.109365  ,
         7.937237  ,   7.5929413 ,   7.211068  ,   6.75933   ,
         5.686251  ,   6.54389   ,   5.98393   ,   7.227647  ,
         8.985021  ,   7.2025957 ,   5.613077  ,   4.5781746 , ... 
```

I will look into tfp.distributions.JointDistributionSequential to see if it offers a solution, and report back here, but I don't believe it can be fixed without changing Poisson to sample ints.

**Comment by brianwa84** [comment]
That's surprising, often we will have a dtype= or sample_dtype= arg
on discrete distribution constructors (feel free to send a PR to fix
Poisson).

https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/RandomWalkMetropolis#sampling_from_the_standard_normal_distribution_using_cauchy_proposal
shows how to change the proposal function for RWM, for now.


Brian Patton | Software Engineer | bjp@google.com

**Comment by daniel-s-cunha** [comment]
Thank you, Brian. Just a few more loose ends...

1.)
Am I able to create a separate proposal function for each variable? Or does it have to be global?

2.)
Can you help me understand the proper way to send a PR?
For example, which two branches should I select for comparison?

**Comment by brianwa84** [comment]
The proposal function is global, i.e. it should generate a new proposal for
each latent variable.

To send a PR, it should be based against the master branch. So you'd fork
the TFP repository under your user, make some changes & commit them, (push
them up to github if you're working on your desk/laptop), then make the PR
on github. jenkins should be able to run tests against your PR, or if you
wanted you could use bazel to test things a la
https://github.com/tensorflow/probability/blob/master/testing/run_tests.sh
(change
tensorflow_probability/... to a more specific directory)

Brian Patton | Software Engineer | bjp@google.com

**Comment by brianwa84** [comment]
You'll need to push to your fork, not the main repository.
