### ISSUE TITLE
Transformed NUTS errors when using dual averaging step size adaption

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#638]
Hi, I _think_ there is a problem when using the 3 kernels:

1. `NoUTurnSampler`
2. `TransformedTransitionKernel`
3. `DualAveragingStepSizeAdaptation`

This is displayed in the following short example:

``` python
import tensorflow as tf
import tensorflow_probability as tfp
import matplotlib.pyplot as plt

# run these tests on CPU
device = tf.config.experimental.list_physical_devices("CPU")
tf.config.experimental.set_visible_devices(device)


tfd = tfp.distributions
tfb = tfp.bijectors

dist = tfd.Exponential(rate=1.0)

nuts = tfp.mcmc.NoUTurnSampler(dist.log_prob, step_size=1.0)

trans_nuts = tfp.mcmc.TransformedTransitionKernel(
    inner_kernel=nuts, bijector=[tfb.Softplus()]
)

adaptive_nuts = tfp.mcmc.DualAveragingStepSizeAdaptation(
    inner_kernel=nuts,
    num_adaptation_steps=100,
    target_accept_prob=0.75,
    step_size_setter_fn=lambda pkr, new_step_size: pkr._replace(
        step_size=new_step_size
    ),
    step_size_getter_fn=lambda pkr: pkr.inner_results.step_size,
    log_accept_prob_getter_fn=lambda pkr: pkr.inner_results.log_accept_ratio,
)

adaptive_trans_nuts = tfp.mcmc.DualAveragingStepSizeAdaptation(
    inner_kernel=trans_nuts,
    num_adaptation_steps=100,
    target_accept_prob=0.75,
    step_size_setter_fn=lambda pkr, new_step_size: pkr.inner_results._replace(
        step_size=new_step_size
    ),
    step_size_getter_fn=lambda pkr: pkr.inner_results.step_size,
    log_accept_prob_getter_fn=lambda pkr: pkr.inner_results.log_accept_ratio,
)


def trace_fn(states, pkr):
    return pkr


@tf.function
def run_mcmc():
    return tfp.mcmc.sample_chain(
        num_results=1_000,
        num_burnin_steps=1_000,
        current_state=tf.ones([]),
        # kernel=nuts,    # runs, results are wrong
        # kernel=trans_nuts,   # runs, results are OK
        # kernel=adaptive_nuts,  # runs, results are wrong
        kernel=adaptive_trans_nuts,  # fails with AttributeError
        trace_fn=trace_fn,
    )


samples, _ = run_mcmc()

plt.hist(samples, density=True, bins=25)
x = tf.range(0.0, 5.0, delta=1e-6)
plt.plot(x, dist.prob(x))
plt.show()
```

Any workarounds or ideas how to fix would be awesome.

versions:
``` python
>>> tf.__version__
'2.1.0-dev20191104'
>>> tfp.__version__
'0.9.0-dev20191104'
```

Full error message:

``` python
>>> samples, _ = run_mcmc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeff/workspace/misc/nuts.py", line 62, in <module>
    samples, _ = run_mcmc()
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2339, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2675, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2565, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in converted code:
    relative to /home/jeff:

    workspace/misc/nuts.py:50 run_mcmc  *
        return tfp.mcmc.sample_chain(
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/sample.py:359 sample_chain
        parallel_iterations=parallel_iterations)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/internal/util.py:350 trace_scan
        parallel_iterations=parallel_iterations)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2478 while_loop_v2
        return_same_structure=True)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2675 while_loop
        back_prop=back_prop)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:200 while_loop
        add_control_dependencies=add_control_dependencies)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:978 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:178 wrapped_body
        outputs = body(*_pack_sequence_as(orig_loop_vars, args))
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/internal/util.py:339 _body
        state = loop_fn(state, elems_array.read(i))
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/sample.py:343 _trace_scan_fn
        parallel_iterations=parallel_iterations)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/internal/util.py:271 smart_for_loop
        parallel_iterations=parallel_iterations
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2478 while_loop_v2
        return_same_structure=True)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2675 while_loop
        back_prop=back_prop)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:200 while_loop
        add_control_dependencies=add_control_dependencies)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:978 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:178 wrapped_body
        outputs = body(*_pack_sequence_as(orig_loop_vars, args))
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/internal/util.py:269 <lambda>
        body=lambda i, *args: [i + 1] + list(body_fn(*args)),
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/dual_averaging_step_size_adaptation.py:437 one_step
        current_state, inner_results)
    .virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow_probability/python/mcmc/transformed_kernel.py:322 one_step
        previous_kernel_results.transformed_state,

    AttributeError: 'NUTSKernelResults' object has no attribute 'transformed_state'
```

**Comment by junpenglao** [comment]
You need one more nesting as we need to set attribute of a inner inner kernel:
```python
adaptive_trans_nuts = tfp.mcmc.DualAveragingStepSizeAdaptation(
    inner_kernel=trans_nuts,
    num_adaptation_steps=100,
    target_accept_prob=0.75,
    step_size_setter_fn=lambda pkr, new_step_size: pkr._replace(
        inner_results=pkr.inner_results._replace(step_size=new_step_size)
        ),
    step_size_getter_fn=lambda pkr: pkr.inner_results.step_size,
    log_accept_prob_getter_fn=lambda pkr: pkr.inner_results.
    log_accept_ratio,
)
```

**Comment by jeffpollock9** [comment]
@junpenglao thanks! That fixes it!
