### ISSUE TITLE
TypeError: solve() missing 1 required positional argument: 'initial_state'

### ISSUE THREAD

**Issue by moonman925** [tensorflow/probability#692]
```
t_init, t0, t1 = 0., 0.5, 1.
y_init = tf.constant([1., 1.], dtype=tf.float64)
A = [[-1., -2.], [-3., -4.]]

def ode_fn(t, y):
  return tf.linalg.matvec(A, y)

results = tfp.math.ode.BDF.solve(ode_fn, t_init, y_init,
                                 solution_times=[t0, t1])
y0 = results.states[0]  # == dot(matrix_exp(A * t0), y_init)
y1 = results.states[1]  # == dot(matrix_exp(A * t1), y_init)
```

example from tfp.math.ode.BDF and tfp.math.ode.solver throws error saying that `inital_state` missed but y_init is the `initial_state`, isn't it?

**Comment by moonman925** [comment]
tensorflow 2.0 and tfp 0.9

**Comment by moonman925** [comment]
after changing BDF. => BDF(). this problem solved but got another error


Traceback (most recent call last):
  File "abc.py", line 14, in <module>
    solution_times=[t0, t1])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/math/ode/base.py", line 361, in solve
    return gradient_helper(*flat_initial_state)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/custom_gradient.py", line 166, in decorated
    return _eager_mode_decorator(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/custom_gradient.py", line 315, in _eager_mode_decorator
    result, grad_fn = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/math/ode/base.py", line 173, in gradient_helper
    previous_solver_internal_state,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/math/ode/bdf.py", line 619, in _solve
    initial_time, ode_fn_vec, rtol, safety_factor)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/math/ode/bdf_util.py", line 52, in first_step_size
    first_derivative = ode_fn_vec(initial_time, initial_state_vec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/math/ode/util.py", line 199, in ode_fn_vec
    ode_fn(time, get_state_from_vec(state_vec, state_shape)))
  File "abc.py", line 11, in ode_fn
    return tf.linalg.matvec(A, y)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py", line 2862, in matvec
    b_is_sparse=b_is_sparse)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py", line 2765, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6126, in mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:MatMul] name: bdf/MatVec/MatMul/
