### ISSUE TITLE
Gaussian Process Regression Model Example Not Working

### ISSUE THREAD

**Issue by mawallace** [tensorflow/probability#735]
When trying to get the second example in the [Gaussian Process Regression Model documentation](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GaussianProcessRegressionModel) working, I'm running into issues that I think are related to v2 differences. The code in the example is shown below.

```python3
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
import matplotlib.pyplot as plt

tfd = tfp.distributions
psd_kernels = tfp.math.psd_kernels

# Suppose we have some data from a known function. Note the index points in
# general have shape `[b1, ..., bB, f1, ..., fF]` (here we assume `F == 1`),
# so we need to explicitly consume the feature dimensions (just the last one
# here).
f = lambda x: np.sin(10*x[..., 0]) * np.exp(-x[..., 0]**2)

observation_index_points = np.random.uniform(-1., 1., 50)[..., np.newaxis]
observations = f(observation_index_points) + np.random.normal(0., .05, 50)

# Define a kernel with trainable parameters. Note we transform the trainable
# variables to apply a positivity constraint.
amplitude = tf.exp(tf.Variable(np.float64(0)), name='amplitude')
length_scale = tf.exp(tf.Variable(np.float64(0)), name='length_scale')
kernel = psd_kernels.ExponentiatedQuadratic(amplitude, length_scale)

observation_noise_variance = tf.exp(
    tf.Variable(np.float64(-5)), name='observation_noise_variance')

# We'll use an unconditioned GP to train the kernel parameters.
gp = tfd.GaussianProcess(
    kernel=kernel,
    index_points=observation_index_points,
    observation_noise_variance=observation_noise_variance)

neg_log_likelihood = -gp.log_prob(observations)

optimizer = tf.train.AdamOptimizer(learning_rate=.05, beta1=.5, beta2=.99)
optimize = optimizer.minimize(neg_log_likelihood)

# We can construct the posterior at a new set of `index_points` using the same
# kernel (with the same parameters, which we'll optimize below).
index_points = np.linspace(-1., 1., 100)[..., np.newaxis]
gprm = tfd.GaussianProcessRegressionModel(
    kernel=kernel,
    index_points=index_points,
    observation_index_points=observation_index_points,
    observations=observations,
    observation_noise_variance=observation_noise_variance)

samples = gprm.sample(10)
# ==> 10 independently drawn, joint samples at `index_points`.

# Now execute the above ops in a Session, first training the model
# parameters, then drawing and plotting posterior samples.
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for i in range(1000):
    _, neg_log_likelihood_ = sess.run([optimize, neg_log_likelihood])
    if i % 100 == 0:
      print("Step {}: NLL = {}".format(i, neg_log_likelihood_))

  print("Final NLL = {}".format(neg_log_likelihood_))
  samples_ = sess.run(samples)

  plt.scatter(np.squeeze(observation_index_points), observations)
  plt.plot(np.stack([index_points[:, 0]]*10).T, samples_.T, c='r', alpha=.2)
```

I think I've figured out that I need to change the `AdamOptimizer` part to
```python3
optimizer = tf.optimizers.Adam(learning_rate=.05, beta_1=.5, beta_2=.99)
optimize = optimizer.minimize(neg_log_likelihood, var_list=[amplitude, length_scale, observation_noise_variance])
```

However, even with this change, I'm still getting the following:
```
2020-01-17 15:57:21.736494: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-17 15:57:21.753115: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcfdeda1e60 executing computations on platform Host. Devices:
2020-01-17 15:57:21.753154: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "tf-gprm.py", line 37, in <module>
    optimize = optimizer.minimize(neg_log_likelihood, var_list=[amplitude, length_scale, observation_noise_variance])
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 319, in minimize
    return self.apply_gradients(grads_and_vars, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 435, in apply_gradients
    self._create_slots(var_list)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/adam.py", line 146, in _create_slots
    self.add_slot(var, 'm')
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 571, in add_slot
    var_key = _var_key(var)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 1051, in _var_key
    if var._in_graph_mode:
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_in_graph_mode'
```

Would someone be able to help out with resolving this?

Versions as follows:
```
tensorflow              2.0.0
tensorflow_probability  0.8.0
```

**Comment by srvasude** [comment]
Hi,
  For now I recommend looking at the Jupyter notebook for this: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Gaussian_Process_Regression_In_TFP.ipynb

We still need to update our docstrings to be TF2 compatible. In particular the optimizer would need to be changed, along with the variables (right now they are invoked as tf.exp(tf.Variable(....))), but should use instead tfp's TransformedVariable)

**Comment by mawallace** [comment]
Thank you. I'll see if I can get that working.

Is there a plan to update the docstrings together? If not, I might be able to add a working example to the GPRM docstring once I figure this out.

**Comment by brianwa84** [comment]
A PR to update the docstring would be great. Note that it should go in the
python file, not the .md file.

**Comment by srvasude** [comment]
Closed by https://github.com/tensorflow/probability/commit/5b3eae41363d5fc5ef6390a62c6f75f326372939
