### ISSUE TITLE
`bfgs_minimize` errors with `@tf.function(experimental_compile=True)`

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#764]
Hi,

If an `initial_inverse_hessian_estimate` is supplied to `tfp.optimizer.bfgs_minimize` then some assert [operations are added](https://github.com/tensorflow/probability/blob/6fdaa6e60aa7a93a67055248ed5b81ce10b497d6/tensorflow_probability/python/optimizer/bfgs.py#L288). AFAIK this means that the function cannot work with `@tf.function(experimental_compile=True)` (see example below) and additionally the checks could be quite expensive for large problems as they involve a [cholesky decomposition](https://github.com/tensorflow/probability/blob/6fdaa6e60aa7a93a67055248ed5b81ce10b497d6/tensorflow_probability/python/optimizer/bfgs.py#L304).

I was wondering if there could be some way to skip these checks? Perhaps a new parameter like `tfp.optimizer.bfgs_minimize(..., validate_args=True)` in a similar fashion to the distributions? Happy to contribute this if it would be useful for anyone (it certainly would be for me).

Thanks!

```python
import tensorflow as tf
import tensorflow_probability as tfp

print(tfp.__version__)
### => '0.9.0'
print(tf.__version__)
### ==> '2.1.0'


def objective(x):
    return tf.reduce_sum(tf.math.squared_difference(x, [1.0, 10.0]))


def objective_value_and_grad(x):
    return tfp.math.value_and_gradient(objective, x)


@tf.function(autograph=False, experimental_compile=True)
def fit_works():
    return tfp.optimizer.bfgs_minimize(
        objective_value_and_grad, initial_position=tf.zeros(2),
    )


@tf.function(autograph=False, experimental_compile=True)
def fit_doesnt_work():
    return tfp.optimizer.bfgs_minimize(
        objective_value_and_grad,
        initial_position=tf.zeros(2),
        initial_inverse_hessian_estimate=tf.eye(2),
    )


optim = fit_works()

print(f"value: {optim.objective_value}, position: {optim.position}")
### => value: 0.0, position: [ 1. 10.]

fit_doesnt_work()
### =>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeff/workspace/misc/bfgs_compile.py", line 33, in <module>
    optim = fit_doesnt_work()
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 564, in __call__
    result = self._call(*args, **kwds)
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/jeff/.virtualenvs/prematch-models/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: name: "__inference_fit_doesnt_work_4833" op: "__inference_fit_doesnt_work_4833" attr { key: "_XlaCompile" value { b: true } } attr { key: "config_proto" value { s: "\n\007\n\003GPU\020\001\n\007\n\003CPU\020\0012\005*\0010J\0008\001" } } attr { key: "executor_type" value { s: "" } }.
Uncompilable nodes:
	minimize/Assert/Const: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_fit_doesnt_work_4833, function: 
		Node: minimize/Assert/Const, function: __inference_fit_doesnt_work_4833
	minimize/Assert_1/Const: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_fit_doesnt_work_4833, function: 
		Node: minimize/Assert_1/Const, function: __inference_fit_doesnt_work_4833
	Assert/data_0: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_fit_doesnt_work_4833, function: 
		Node: minimize/Assert_1/AssertGuard, function: __inference_fit_doesnt_work_4833
		Node: Assert/data_0, function: minimize_Assert_1_AssertGuard_false_2450
	Assert/data_0: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_fit_doesnt_work_4833, function: 
		Node: minimize/Assert/AssertGuard, function: __inference_fit_doesnt_work_4833
		Node: Assert/data_0, function: minimize_Assert_AssertGuard_false_2434
 [Op:__inference_fit_doesnt_work_4833]
```

**Comment by csuter** [comment]
Adding validate_args here would be great. Thanks Jeff!

**Comment by jeffpollock9** [comment]
Cool, thanks @csuter. Feel free to assign this issue to me and I will try to get to it when I have time in the next week or so.
