### ISSUE TITLE
error installing tfp-nightly-gpu

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#80]
Getting this trying to install tf-nightly-gpu in a fresh virtual environment:

```
(probability) ~ ♫ pip install tfp-nightly-gpu
Collecting tfp-nightly-gpu
Requirement already satisfied: numpy>=1.11.1 in ./.virtualenv/probability/lib/python3.4/site-packages (from tfp-nightly-gpu) (1.14.4)
Requirement already satisfied: tf-nightly in ./.virtualenv/probability/lib/python3.4/site-packages (from tfp-nightly-gpu) (1.9.0.dev20180606)
Requirement already satisfied: six>=1.10.0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tfp-nightly-gpu) (1.11.0)
Requirement already satisfied: absl-py>=0.1.6 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (0.2.2)
Requirement already satisfied: wheel>=0.26 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (0.31.1)
Requirement already satisfied: tb-nightly<1.10.0a0,>=1.9.0a0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (1.9.0a20180606)
Requirement already satisfied: termcolor>=1.1.0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (1.12.1)
Requirement already satisfied: protobuf>=3.4.0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (3.5.2.post1)
Requirement already satisfied: gast>=0.2.0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (0.2.0)
Requirement already satisfied: astor>=0.6.0 in ./.virtualenv/probability/lib/python3.4/site-packages (from tf-nightly->tfp-nightly-gpu) (0.6.2)
Requirement already satisfied: werkzeug>=0.11.10 in ./.virtualenv/probability/lib/python3.4/site-packages (from tb-nightly<1.10.0a0,>=1.9.0a0->tf-nightly->tfp-nightly-gpu) (0.14.1)
Requirement already satisfied: markdown>=2.6.8 in ./.virtualenv/probability/lib/python3.4/site-packages (from tb-nightly<1.10.0a0,>=1.9.0a0->tf-nightly->tfp-nightly-gpu) (2.6.11)
Requirement already satisfied: setuptools in ./.virtualenv/probability/lib/python3.4/site-packages (from protobuf>=3.4.0->tf-nightly->tfp-nightly-gpu) (39.2.0)
Installing collected packages: tfp-nightly-gpu
Exception:
Traceback (most recent call last):
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/SMARTODDS/pollockj/.virtualenv/probability/lib/python3.4/site-packages/pip/_internal/wheel.py", line 316, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tfp-nightly-gpu .dist-info directory not found
```

Any help would be great, thanks.

**Comment by kmario23** [comment]
Hi @jeffpollock9 , could you please post how you have resolved this issue?

**Comment by jeffpollock9** [comment]
@kmario23 apologies for not commenting. I spent a while trying to fix this but couldn't, then closed the issue due to inactivity.

**Comment by jeffpollock9** [comment]
After reading #86 I managed to fix this via `pip install tf-nightly-gpu --upgrade --no-cache-dir --isolated`

**Comment by kmario23** [comment]
@jeffpollock9 Thanks!
