### ISSUE TITLE
Error in Linear_Mixed_Effects_Models notebook

### ISSUE THREAD

**Issue by huangy22** [tensorflow/probability#82]
Here is my version:
```
>>> sys.version
'3.6.5 (default, Apr 25 2018, 14:23:58) \n[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]'
>>> tf.__version__
'1.10.0-dev20180610'
```

When running the example notebook for Linear Mixed Effects Models, I had the following error:
```
log_joint = ed.make_log_joint_fn(model_template)

def target_log_prob_fn(effect_students, effect_instructors, effect_departments):
  """Unnormalized target density as a function of states."""
  return log_joint(  # fix `features` and `ratings` to the training data
    features=features_train,
    effect_students=effect_students,
    effect_instructors=effect_instructors,
    effect_departments=effect_departments,
    ratings=labels_train)

# Set up E-step (MCMC).
effect_students = tf.get_variable(  # `trainable=False` so unaffected by M-step
    "effect_students", [num_students], trainable=False)
effect_instructors = tf.get_variable(
    "effect_instructors", [num_instructors], trainable=False)
effect_departments = tf.get_variable(
    "effect_departments", [num_departments], trainable=False)

hmc = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.015,
    num_leapfrog_steps=3)

current_state = [effect_students, effect_instructors, effect_departments]
with warnings.catch_warnings():
  # TensorFlow raises a warning about converting sparse IndexedSlices to a
  # dense Tensor during gradient computation. This can consume a large amount
  # of memory. We're okay with that as the number of categories is small.
  warnings.simplefilter("ignore")
  next_state, kernel_results = hmc.one_step(
      current_state=current_state,
      previous_kernel_results=hmc.bootstrap_results(current_state))

expectation_update = tf.group(
    effect_students.assign(next_state[0]),
    effect_instructors.assign(next_state[1]),
    effect_departments.assign(next_state[2]))

# Set up M-step (gradient descent).
# The following should work. However, TensorFlow raises an error about taking
# gradients through IndexedSlices tensors. This may be a TF bug. For now,
# we recompute the target's log probability at the current state.
# loss = -kernel_results.accepted_results.target_log_prob
with tf.control_dependencies([expectation_update]):
  loss = -target_log_prob_fn(effect_students,
                             effect_instructors,
                             effect_departments)
  optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
  minimization_update = optimizer.minimize(loss)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-f161e7250d23> in <module>()
     12 # Set up E-step (MCMC).
     13 effect_students = tf.get_variable(  # `trainable=False` so unaffected by M-step
---> 14     "effect_students", [num_students], trainable=False)
     15 effect_instructors = tf.get_variable(
     16     "effect_instructors", [num_instructors], trainable=False)

~/.virtualenvs/env_edward/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1334       partitioner=partitioner, validate_shape=validate_shape,
   1335       use_resource=use_resource, custom_getter=custom_getter,
-> 1336       constraint=constraint)
   1337 get_variable_or_local_docstring = (
   1338     """%s

~/.virtualenvs/env_edward/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1096           partitioner=partitioner, validate_shape=validate_shape,
   1097           use_resource=use_resource, custom_getter=custom_getter,
-> 1098           constraint=constraint)
   1099 
   1100   def _get_partitioned_variable(self,

~/.virtualenvs/env_edward/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
    433           caching_device=caching_device, partitioner=partitioner,
    434           validate_shape=validate_shape, use_resource=use_resource,
--> 435           constraint=constraint)
    436 
    437   def _get_partitioned_variable(

~/.virtualenvs/env_edward/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint)
    402           trainable=trainable, collections=collections,
    403           caching_device=caching_device, validate_shape=validate_shape,
--> 404           use_resource=use_resource, constraint=constraint)
    405 
    406     if custom_getter is not None:

~/.virtualenvs/env_edward/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint)
    741                          "reuse=tf.AUTO_REUSE in VarScope? "
    742                          "Originally defined at:\n\n%s" % (
--> 743                              name, "".join(traceback.format_list(tb))))
    744       found_var = self._vars[name]
    745       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable effect_students already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-9-26e12e3c9108>", line 14, in <module>
    "effect_students", [num_students], trainable=False)
  File "/Users/yuanhuang/.virtualenvs/env_edward/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/yuanhuang/.virtualenvs/env_edward/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):

```
Any help would be appreciated!

**Comment by dustinvtran** [comment]
TF is complaining that you're rebuilding already existing TF variables. Have you wrapped the log joint function in a make template?

**Comment by huangy22** [comment]
Thank you for your reply! I was following the notebook exactly as it is. In the "Model" session, there's this line:
```
# Wrap model in a template. All calls to the model template will use the same
# TensorFlow variables.
model_template = tf.make_template("model", model)
```
before calling the `draw_graph` block (btw, the computational graph was generated successfully). Then in the "Parameter Estimation" block, I had the above error.
