### ISSUE TITLE
Error while building tensorflow_probability from source

### ISSUE THREAD

**Issue by tirthasheshpatel** [tensorflow/probability#845]
I tried to build the library from source on my local computer following [this page](https://www.tensorflow.org/probability/install). I also tried installing all the dependencies individually but I am facing the same issue each time when I try to import tensorflow_probability.

```python
ImportError: cannot import name 'adjoint_registrations' from 'tensorflow_probability.python.internal.backend.numpy' (/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/__init__.py)
```

<details>
<summary>Full Traceback</summary>

```python
>>> import tensorflow_probability as tfp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/__init__.py", line 77, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/__init__.py", line 21, in <module>
    from tensorflow_probability.python import bijectors
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/bijectors/__init__.py", line 23, in <module>
    from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/bijectors/absolute_value.py", line 23, in <module>
    from tensorflow_probability.python.bijectors import bijector
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/bijectors/bijector.py", line 33, in <module>
    from tensorflow_probability.python.internal import distribution_util
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/distribution_util.py", line 28, in <module>
    from tensorflow_probability.python.internal import prefer_static
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/prefer_static.py", line 30, in <module>
    from tensorflow_probability.python.internal.backend import numpy as nptf
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/__init__.py", line 22, in <module>
    from tensorflow_probability.python.internal.backend.numpy import compat
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/compat.py", line 22, in <module>
    from tensorflow_probability.python.internal.backend.numpy import v2
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/v2.py", line 29, in <module>
    from tensorflow_probability.python.internal.backend.numpy import linalg
  File "/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/linalg.py", line 30, in <module>
    from tensorflow_probability.python.internal.backend.numpy import adjoint_registrations as _adjoint_registrations
ImportError: cannot import name 'adjoint_registrations' from 'tensorflow_probability.python.internal.backend.numpy' (/mnt/c/users/tirth/desktop/interests/tfp/tensorflow_probability/python/internal/backend/numpy/__init__.py)
>>>
```

</details>

### Platform

OS: Linux (WSL)
Python version: 3.7.5
Pip version: 20.0.2

**Comment by csuter** [comment]
Make sure you're not still cd'ed into the repo root when you are running
Python. It'll mistakenly try to import tfp from the adjacent directory
called `tensorflow_probability` which is usually the source of this import
error.

**Comment by tirthasheshpatel** [comment]
Great! That worked! Is there some page showing how to run the tests on local machines? I am using pytest but facing a tensorflow import issue! I have never used Bazel before so was curious to know more about using it to run tests.

**Comment by csuter** [comment]
https://github.com/tensorflow/probability/blob/master/CONTRIBUTING.md#unit-tests has some commands for using bazel. I'm not sure if more args are needed now -- can you give those a try and report back? Our Travis tests use a handful more, which you can find [here](https://github.com/tensorflow/probability/blob/master/testing/run_tests.sh#L133) (there's some extra complexity in that script because we shard the tests to decrease end-to-end test time).
