### ISSUE TITLE
KLDivergenceAddLoss not returning a distribution

### ISSUE THREAD

**Issue by paidi** [tensorflow/probability#865]
I am getting an error when I use the `KLDivergenceAddLoss` layer. My understanding is that this should add a loss and return the distribution at the previous layer in the network. However, in the example below the second function raises an error due to the fact that `y` is a `Tensor` following the inclusion of `KLDivergenceAddLoss` in the network.

I am using 

- Python 3.7.7
- tensorflow 2.1.0
- tensorflow-probability 0.9.0

```python
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions
tfpl = tfp.layers
tfk = tf.keras
tfkl = tf.keras.layers

def make_model_no_kl():
    x = tfk.Input([5])
    y = tfk.Sequential([
        tfkl.Dense(2),
        tfpl.DistributionLambda(
            make_distribution_fn=lambda t: tfd.Categorical(logits=t)
        )
    ])(x)
    print(y.sample())
    return tfk.Model(inputs=x, outputs=y)


def make_model_with_kl():
    x = tfk.Input([5])
    y = tfk.Sequential([
        tfkl.Dense(2),
        tfpl.DistributionLambda(
            make_distribution_fn=lambda t: tfd.Categorical(logits=t)
        ),
        tfpl.KLDivergenceAddLoss(tfd.Categorical(logits=[1,2]))
    ])(x)
    print(y.sample())
    return tfk.Model(inputs=x, outputs=y)

m1 = make_model_no_kl()
m2 = make_model_with_kl()

```

```bash
2020-04-05 22:34:49.027766: W tensorflow/python/util/util.cc:319] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2020-04-05 22:34:49.031974: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-05 22:34:49.043548: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb292f93880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-05 22:34:49.043567: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Tensor("Reshape_2:0", shape=(None,), dtype=int32)
Traceback (most recent call last):
  File "simple.py", line 35, in <module>
    m2 = make_model_with_kl()
  File "simple.py", line 31, in make_model_with_kl
    print(y.sample())
AttributeError: 'Tensor' object has no attribute 'sample'
```

**Comment by paidi** [comment]
I'm not 100% sure, but it looks like it might be getting converted here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L2260

**Comment by cboulay** [comment]
Here's some additional info and alternative approaches for anyone who came to this issue hoping to add KLDivergence loss to their model.

While searching to see if anyone else posted an issue, I saw in a previous issue that someone had used this layer without capturing its output: https://github.com/tensorflow/probability/issues/544#issue-489434519

I just tested that and it doesn't seem to work.

However, `KLDivergenceRegularizer` does seem to work:
```Python
x2 = tfpl.MyFavouriteDistLayer(
    activity_regularizer=tfpl.KLDivergenceRegularizer(prior)
)(x1)
```

Another method that I used was to have my model also return the distribution-in-question as one of its outputs, then use custom loss functions for each output, where the distribution's loss function is `lambda y_true, model_out: tfd.kl_divergence(model_out, prior)` (Note: that's the 'exact_kl' formulation. If your output and prior distributions aren't identical types then you'll need the inexact formulation that requires sampling). One advantage of this is that Keras' `fit` will print out the prediction and KL losses independently.

I don't yet know how these different approaches work with trainable priors.
