### ISSUE TITLE
cifar10_bnn.py: No module named 'tensorflow_probability.examples'

### ISSUE THREAD

**Issue by peter197321** [tensorflow/probability#889]
I'd like to understand how/where to include properly tensorflow_probability.examples in cifar10_bnn.py ?

```
/probability/tensorflow_probability/examples$ python cifar10_bnn.py
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "cifar10_bnn.py", line 51, in <module>
    from tensorflow_probability.examples.models.bayesian_resnet import bayesian_resnet
ModuleNotFoundError: No module named 'tensorflow_probability.examples'
```

**Comment by csuter** [comment]
Hi, please use the command indicated here to run the example: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/cifar10_bnn.py#L22

**Comment by peter197321** [comment]
```
probability/tensorflow_probability/examples$ bazel run //tensorflow_probability/examples:cifar10_bnn -- ${FLAGS}
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/work/probability/tools/bazel.rc
INFO: Analyzed target //tensorflow_probability/examples:cifar10_bnn (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR:
/work/probability/tensorflow_probability/python/internal/backend/numpy/BUILD:392:2: Executing genrule //tensorflow_probability/python/internal/backend/numpy:rewrite_linear_operator_block_lower_triangular failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/.cache/bazel/_bazel_nxa18908/ac43ec596edc433f6e955f1e388bc118/sandbox/linux-sandbox/295/execroot/tensorflow_probability/bazel-out/host/bin/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.runfiles/tensorflow_probability/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.py", line 151, in <module>
    app.run(main)
  File "/home/anaconda3/envs/tf-cpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/tf-cpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/.cache/bazel/_bazel_nxa18908/ac43ec596edc433f6e955f1e388bc118/sandbox/linux-sandbox/295/execroot/tensorflow_probability/bazel-out/host/bin/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.runfiles/tensorflow_probability/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.py", line 147, in main
    gen_module(FLAGS.module_name)
  File "/home/.cache/bazel/_bazel_nxa18908/ac43ec596edc433f6e955f1e388bc118/sandbox/linux-sandbox/295/execroot/tensorflow_probability/bazel-out/host/bin/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.runfiles/tensorflow_probability/tensorflow_probability/python/internal/backend/meta/gen_linear_operators.py", line 73, in gen_module
    'tensorflow.python.ops.linalg.{}'.format(module_name))
  File "/home/anaconda3/envs/tf-cpu/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow.python.ops.linalg.linear_operator_block_lower_triangular'
Target //tensorflow_probability/examples:cifar10_bnn failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.162s, Critical Path: 2.04s
INFO: 27 processes: 27 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

**Comment by peter197321** [comment]
```
/work/probability/tensorflow_probability/examples$ bazel run tensorflow_probability/examples:cifar10_bnn
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/work/work/probability/tools/bazel.rc
ERROR: Skipping 'tensorflow_probability/examples:cifar10_bnn': no such package 'tensorflow_probability/examples/tensorflow_probability/examples': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /work/probability/tensorflow_probability/examples/tensorflow_probability/examples
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow_probability/examples/tensorflow_probability/examples': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /work/probability/tensorflow_probability/examples/tensorflow_probability/examples
INFO: Elapsed time: 0.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

```
