### ISSUE TITLE
tfp-nightly Import error:  unintentional pandas dependency?

### ISSUE THREAD

**Issue by cmobarry** [tensorflow/probability#90]
I am guessing that an unintentional pandas dependency problem made it into tfp-nightly.
Or should pandas be a known dependency via the pip wheels ?
Okay, I am confused that a "import pandas" fails inside "import tensorflow_probability as tfp"  but works if I do a "import pandas" beforehand.

(1) Installed latest tfp-nightly in a clean Anaconda 5.1 virtual environment without sudo.
```
conda install pip matplotlib scikit-learn pandas ;
pip install tensorflow ;     
pip install --user --upgrade cython tfp-nightly ;
..
Successfully installed tfp-nightly-0.1.0rc1.dev20180701
```

(2) Complains that pandas.core not available.
```
(venv2_pip) $ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_probability as tfp
tf.estimator package not installed.
Traceback (most recent call last):
..
  File "$HOME/.local/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/pandas_io.py", line 29, in <module>
    import pandas as pd
...
AttributeError: module 'pandas' has no attribute 'core'
>>> 
```

(3) But it's okay when importing Pandas before tfp.
```
(venv2_pip) $ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import tensorflow_probability as tfp
>>> 
```

(4) The full backtrace follows.
```
(venv2_pip) $ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_probability as tfp
tf.estimator package not installed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py", line 41, in <module>
    from tensorflow_probability.python.distributions.linear_gaussian_ssm import LinearGaussianStateSpaceModel
File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py", line 34, in <module>
    tfl = tf.contrib.linalg
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import distributions
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/distributions/__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 35, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 43, in <module>
    from tensorflow.contrib.learn.python.learn import monitors as monitor_lib
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 50, in <module>
    from tensorflow.python.estimator import estimator as core_estimator
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/estimator/__init__.py", line 25, in <module>
    import tensorflow.python.estimator.estimator_lib
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator_lib.py", line 41, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/inputs.py", line 23, in <module>
    from tensorflow.python.estimator.inputs.pandas_io import pandas_input_fn
  File "/home/cmobarry/.local/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/pandas_io.py", line 29, in <module>
    import pandas as pd
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/home/cmobarry/.conda/envs/venv2_pip/lib/python3.6/site-packages/pandas/core/series.py", line 67, in <module>
    import pandas.core.ops as ops
AttributeError: module 'pandas' has no attribute 'core'
>>> 
```

**Comment by brianwa84** [comment]
I'm assuming this is gone now, but please reopen if not. The pandas dep is indeed not expected.
