### ISSUE TITLE
DeferredTensor and TransformedVariable when used as GradientTape source

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/probability#903]
Both of the examples below fail. Seems like these should work?

## 1. `tfp.util.DeferredTensor`
```python
import tensorflow as tf
import tensorflow_probability as tfp


log_x = tf.Variable(0.0)
x = tfp.util.DeferredTensor(log_x, tf.exp)
with tf.GradientTape() as g:
    y = x * x

dy_dx = g.gradient(y, x)
```

```
$ python ./tests/test_tfp_deferred_tensor_gradient.py
Traceback (most recent call last):
  File "./tests/test_tfp_deferred_tensor_gradient.py", line 10, in <module>
    dy_dx = g.gradient(y, x)
  File "/Users/hartikainen/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1048, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/Users/hartikainen/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
AttributeError: 'DeferredTensor' object has no attribute '_id'
```

## 2. `tfp.util.TransformedVariable`
```python
import tensorflow as tf
import tensorflow_probability as tfp


x = tfp.util.TransformedVariable(tf.exp(0.0), tfp.bijectors.Exp())
with tf.GradientTape() as g:
    y = x * x

dy_dx = g.gradient(y, x)
```

```
$ python ./tests/test_tfp_deferred_tensor_gradient.py
Traceback (most recent call last):
  File "./tests/test_tfp_deferred_tensor_gradient.py", line 17, in <module>
    dy_dx = g.gradient(y, x)
  File "/Users/hartikainen/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1048, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/Users/hartikainen/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
AttributeError: 'TransformedVariable' object has no attribute '_id'
```

```
$ pip freeze | grep "tf\|tensor\|nightly"
tensorboard==2.2.0
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0rc3
tensorflow-addons==0.9.1
tensorflow-estimator==2.2.0
tensorflow-probability==0.10.0rc0
```

**Comment by brianwa84** [comment]
It's not expected this would work. These are instances of tf.Module.
Instead, you can use
g.gradient(y, x.trainable_variables[0])

**Comment by hartikainen** [comment]
Ah, interesting. For some reason I thought of them to be more like tensors and expected the gradients to work, but I think this makes sense. Sorry for the noise!
