### ISSUE TITLE
Many sample functions which use gamma samples cannot use XLA

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/probability#934]
Hi,

I was really excited to see in the 0.10.0 release notes that there is a XLA-able gamma sampler - awesome!

However as far as I can see there are now two implementations of a gamma sampler in TFP:

1. the XLA compatible [Gamma.random_gamma](https://github.com/tensorflow/probability/blob/026312b7384367cb6b3076eb0902bceae3ff8bb8/tensorflow_probability/python/distributions/gamma.py#L339)
2. the non-XLA compatible [samplers.gamma](https://github.com/tensorflow/probability/blob/026312b7384367cb6b3076eb0902bceae3ff8bb8/tensorflow_probability/python/internal/samplers.py#L107)

and I think many of the distributions which use a gamma sampler internally use the non-XLA implementation (a quick grep shows):

```
distributions/inverse_gamma.py:205:    return 1. / samplers.gamma(
distributions/negative_binomial.py:159:    rate = samplers.gamma(
distributions/beta.py:243:    gamma1_sample = samplers.gamma(
distributions/beta.py:245:    gamma2_sample = samplers.gamma(
distributions/chi2.py:129:    return samplers.gamma(
distributions/gamma_gamma.py:187:    rate = samplers.gamma(
distributions/gamma_gamma.py:194:    return samplers.gamma(
distributions/student_t.py:73:  gamma_sample = samplers.gamma([n],
distributions/dirichlet.py:224:    gamma_sample = samplers.gamma(
distributions/wishart.py:196:    g = samplers.gamma(
distributions/dirichlet_multinomial.py:283:        samplers.gamma(
```

I am wondering if it is possible to switch these to the XLA version? In that case I can get stuff like this to work:

``` python
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

print(tf.__version__)
# 2.3.0-dev20200514

print(tfp.__version__)
# 0.11.0-dev20200514


@tf.function(autograph=False, experimental_compile=True)
def dirichlet():
    return tfd.Dirichlet(concentration=[1., 2.]).sample(3)

dirichlet()
# ...
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/jeff/workspace/misc/gamma_compile2.py", line 30, in <module>
#     dirichlet()
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 761, in __call__
#     result = self._call(*args, **kwds)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 800, in _call
#     results = self._stateful_fn(*args, **kwds)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2812, in __call__
#     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
#     cancellation_manager=cancellation_manager)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1915, in _call_flat
#     ctx, args, cancellation_manager=cancellation_manager))
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 549, in call
#     ctx=ctx)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
#     inputs, attrs, num_outputs)
# tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_dirichlet_410}} = __inference_dirichlet_410[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001", executor_type=""]().
# Uncompilable nodes:
# Dirichlet_1/sample/gamma/stateless_random_gamma/StatelessRandomGammaV2: unsupported op: No registered 'StatelessRandomGammaV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node Dirichlet_1/sample/gamma/stateless_random_gamma/StatelessRandomGammaV2}}
# 	Stacktrace:
# 		Node: __inference_dirichlet_410, function:
# 		Node: Dirichlet_1/sample/gamma/stateless_random_gamma/StatelessRandomGammaV2, function: __inference_dirichlet_410
#  [Op:__inference_dirichlet_410]
```

Or perhaps this is a TF bug as the docs in `tf.random.stateless_gamma` state:

> Args:
>  ...
>  seed: A shape [2] Tensor, the seed to the random number generator. Must have dtype `int32` or `int64`. (When using XLA, only `int32` is allowed.)

which makes me think this function should work with XLA but doesn't and your own implementation is a workaround?

``` python
@tf.function(autograph=False, experimental_compile=True)
def stateless_gamma():
    return tf.random.stateless_gamma(
        shape=[1, 2], seed=tf.constant([3, 4], tf.int32), alpha=[5., 6.]
    )


stateless_gamma()
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/jeff/workspace/misc/gamma_compile2.py", line 54, in <module>
#     stateless_gamma()
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 761, in __call__
#     result = self._call(*args, **kwds)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 832, in _call
#     return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
#     cancellation_manager=cancellation_manager)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1915, in _call_flat
#     ctx, args, cancellation_manager=cancellation_manager))
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 549, in call
#     ctx=ctx)
#   File "/home/jeff/.virtualenvs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
#     inputs, attrs, num_outputs)
# tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_stateless_gamma_67}} = __inference_stateless_gamma_67[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001", executor_type=""]().
# Uncompilable nodes:
# stateless_random_gamma/StatelessRandomGammaV2: unsupported op: No registered 'StatelessRandomGammaV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node stateless_random_gamma/StatelessRandomGammaV2}}
# 	Stacktrace:
# 		Node: __inference_stateless_gamma_67, function: 
# 		Node: stateless_random_gamma/StatelessRandomGammaV2, function: __inference_stateless_gamma_67
#  [Op:__inference_stateless_gamma_67]
 ```

If at all useful I think I could make the required changes to switch over to the XLA sampler, but I am not quite sure exactly what is going on with all this.

Thanks!

**Comment by davmre** [comment]
Hi Jeff,

Someone who knows more can correct me, but as far as I know, the primary reason for implementing `Gamma.random_gamma` was to have a gamma sampler that worked under XLA. Until very recently it unfortunately *didn't* work inside of `tf.vectorized_map`, which I believe is one reason for it hasn't been incorporated more widely. But this is no longer an issue as of a couple of weeks ago, when TF [added support](https://github.com/tensorflow/tensorflow/commit/679da1ca0ee153c23de24ad0f884ef19a235b73a) for vectorizing While loops.

If you want to XLA-compile other distributions in your own private use, it would certainly be valid to modify `samplers.gamma` to call `Gamma.random_gamma`. I'm not sure if there are reasons beyond inertia why this hasn't been done in TFP yet. Maybe @csuter or @brianwa84 would know?

Dave

**Comment by srvasude** [comment]
I'm in the process of allowing switching between tf.random.gamma and the gamma sampler in TFP. I'll probably be following up with using these samplers elsewhere.

**Comment by jeffpollock9** [comment]
many thanks for the replies, @davmre and @srvasude - feel free to close this ticket if you have that work documented elsewhere, else I'll close it once your changes have been made

**Comment by srvasude** [comment]
Gamma samplers have been XLA compatible for a while now. Closing this issue.
