### ISSUE TITLE
Manually updating prob attribute

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/probability#976]
I'm not using tfp with Keras—I'm using `tfp.distributions.Multinomial` to represent a discrete probability density function. The following script fails:
```python
import tensorflow as tf
import tensorflow_probability as tfp


mydist = tfp.distributions.Multinomial(
    1.,
    probs=[0.2, 0.2, 0.6],
)
tf.print(mydist)
mydist.probs = [0.4, 0.4, 0.2]
tf.print(mydist)
```
output:
```
2020-06-19 10:04:20.135858: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-19 10:04:20.152909: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe9cb6a8850 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-19 10:04:20.152942: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
<tfp.distributions.Multinomial 'Multinomial' batch_shape=[] event_shape=[3] dtype=float32>
Traceback (most recent call last):
  File "myprob.py", line 10, in <module>
    mydist.probs = [0.4, 0.4, 0.2]
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 89, in __setattr__
    super(AutoTrackable, self).__setattr__(name, value)
AttributeError: can't set attribute
```

**Comment by csuter** [comment]
Thanks for the question @sumanthratna -- most TFP objects are not mutable; such assignments are not expected to work correctly. Instead, you should use the `copy` method to construct a  new instance with different properties:

```
mydist = mydist.copy(probs=[.4, .4, .2])
```

Let us know if you have further issues!
